import winston from "winston";
import { BaseActivePersona } from "../../base_persona.ts";

const logger = winston.child({ module: "Director" });

/**
 * Model: O Diretor PhD 🏛️ (Bun Version).
 */
export class DirectorPersona extends BaseActivePersona {
    constructor(projectRoot: string | null = null) {
        super(projectRoot);
        this.name = "Director";
        this.emoji = "🏛️";
        this.role = "Master Orchestrator";
    }

    async performAudit(): Promise<any[]> {
        const findings: any[] = [];
        const criticalFiles = Object.keys(this.contextData).filter(f =>
            f.endsWith(".ts") && (f.includes("core") || f.includes("security") || f.includes("agent")) &&
            !this.ignoredFiles.includes(f)
        );

        // Strategic Sampling
        const sampleSize = Math.min(criticalFiles.length, 3);
        const targetSample = criticalFiles.sort(() => 0.5 - Math.random()).slice(0, sampleSize);

        for (const file of targetSample) {
            const content = await this.readProjectFile(file);
            if (content) {
                // Mock analyzer call
                logger.info(`Director: Analisando intenção estratégica em ${file}`);
            }
        }

        return findings;
    }

    async reasonAboutObjective(objective: string, file: string, content: string): Promise<any> {
        /** O Diretor sintetiza, não realiza raciocínio individual em arquivos. */
        return null;
    }

    deduplicateResults(auditResults: any[]): any[] {
        const uniqueResults: any[] = [];
        const seen = new Set<string>();
        for (const r of auditResults) {
            let key = "";
            if (typeof r === 'object' && r !== null) {
                const cleanIssue = (r.issue || '').replace(/\.$/, '');
                key = `${r.file}:${r.line}:${cleanIssue}`;
            } else {
                key = String(r).replace(/\.$/, '');
            }

            if (!seen.has(key)) {
                uniqueResults.push(r);
                seen.add(key);
            }
        }
        return uniqueResults;
    }

    format360Report(healthData: any, auditResults: any[]): string {
        const uniqueResults = this.deduplicateResults(auditResults);
        const now = new Date().toISOString();

        let md = `# 🏛️ 360° Diagnostic Report (Bun Sovereignty)\n\n`;
        md += `**Date:** ${now}\n`;
        md += `**Global Health Score:** \`${healthData.health_score}%\`\n`;
        md += `**Total Findings:** ${uniqueResults.length}\n\n`;

        md += `## 📡 Health Breakdown\n`;
        const breakdown = healthData.health_breakdown || {};
        if (Object.keys(breakdown).length === 0) {
            md += `- **System Balance**: ✅ \`100%\` (No regressions detected)\n`;
            md += `- **Topology Integrity**: ✅ \`100%\` (Semantic mapping verified)\n`;
        } else {
            for (const [key, val] of Object.entries(breakdown)) {
                const score = Number(val);
                const status = score > 80 ? '✅' : score > 50 ? '⚠️' : '🚨';
                md += `- **${key}**: ${status} \`${score}%\`\n`;
            }
        }

        md += `\n## 🔍 Audit Findings\n`;
        if (uniqueResults.length === 0) {
            md += `*No issues detected. The system is structurally sound.*\n`;
        } else {
            md += `| Severity | Component | Finding |\n`;
            md += `|---|---|---|\n`;
            for (const r of uniqueResults) {
                const sev = r.severity === 'critical' ? '🔴' : r.severity === 'high' ? '🟠' : '🟡';
                const issueText = typeof r === 'object' ? r.issue || JSON.stringify(r) : String(r);
                md += `| ${sev} ${r.severity?.toUpperCase() || 'INFO'} | \`${r.file}:${r.line || '?'}\` | ${issueText} |\n`;
            }
        }

        md += `\n---\n*Generated by Sovereign Director Persona.*`;
        return md;
    }

    getSystemPrompt(): string {
        return `You are the Director 🏛️. Your mission is: Master Orchestrator.`;
    }
}
