from ..base import BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext
import re

class DirectorPersona(BaseActivePersona):
    """
    🏛️ Dr. Director — PhD in Systemic Orchestration & AI Governance
    Generated by Sovereign Forge.
    """
    def __init__(self, project_root: str = None):
        super().__init__(project_root)
        self.id = "director"
        self.name = "Director"
        self.emoji = "🏛️"
        self.role = "Master Orchestrator"
        self.phd_identity = "Systemic Orchestration & AI Governance"
        self.stack = "Python"
        self.healing_prompt = "Fix the following architectural drift or governance violation. Enforce layered boundaries and ensure proper separation of concerns. Return ONLY the corrected code or a specific diff."

    async def execute(self, context: ProjectContext) -> list:
        self.set_context(context)
        return await self.perform_audit()

    def get_audit_rules(self) -> dict:
        return {
            "extensions": [".py"],
            "rules": [
                # [
          {
                    "regex": "security(?!.*crypto)",
                    "issue": "Alerta Estratégico: Arquivo de segurança sem referências criptográficas óbvias PhD.",
                    "severity": "low"
          }
]
            ]
        }

    async def reason_about_objective(self, objective: str, file: str, context: str) -> dict:
        return {
            "file": file,
            "severity": "INFO",
            "issue": f"PhD Director (Python): Analyzing {objective} in {file}.",
            "context": "analyzing objective"
        }

    async def delegate_healing_to_hub(self, file: str, issue: str) -> str:
        # Delegation logic here via gRPC back to Hub
        return None
