from ..base import BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext
import re

class WardenPersona(BaseActivePersona):
    """
    🛡️ Dr. Warden — PhD in Sovereignty & Strategic Security (TypeScript)
    Generated by Sovereign Forge.
    """
    def __init__(self, project_root: str = None):
        super().__init__(project_root)
        self.id = "warden"
        self.name = "Warden"
        self.emoji = "🛡️"
        self.role = "PhD Strategic Guardian"
        self.phd_identity = "Sovereignty & Strategic Security (TypeScript)"
        self.stack = "Python"
        self.healing_prompt = "Fix the following access control or authorization issue. Correct RBAC violations and enforce the principle of least privilege. Return ONLY the corrected code or a specific diff."

    async def execute(self, context: ProjectContext) -> list:
        self.set_context(context)
        return await self.perform_audit()

    def get_audit_rules(self) -> dict:
        return {
            "extensions": [".py"],
            "rules": [
                # [
          {
                    "regex": "process\\.env",
                    "issue": "Segurança: Acesso a variáveis de ambiente; verifique segredos PhD.",
                    "severity": "medium"
          }
]
            ]
        }

    async def reason_about_objective(self, objective: str, file: str, context: str) -> dict:
        return {
            "file": file,
            "severity": "INFO",
            "issue": f"PhD Warden (Python): Analyzing {objective} in {file}.",
            "context": "analyzing objective"
        }

    async def delegate_healing_to_hub(self, file: str, issue: str) -> str:
        # Delegation logic here via gRPC back to Hub
        return None
