import { BaseActivePersona } from "../../base.ts";
import type { AuditRule, StrategicFinding, AuditFinding, HealingResult, ProjectContext } from "../../base.ts";

/**
 * 🌍 Dr. Globe — PhD in Internationalization & Localization (TypeScript)
 * Generated by Sovereign Forge.
 */
export class GlobePersona extends BaseActivePersona {
    constructor(projectRoot: string | undefined = undefined) {
        super(projectRoot);
        this.id = "globe";
        this.name = "Globe";
        this.emoji = "🌍";
        this.role = "PhD Internationalization Engineer";
        this.phd_identity = "Internationalization & Localization (TypeScript)";
        this.stack = "Bun";
        this.healingPrompt = "Fix the following i18n or localization issue. Replace hardcoded strings with locale keys and ensure locale-aware formatting. Return ONLY the corrected code or a specific diff.";
    }

    override async execute(context: ProjectContext): Promise<(AuditFinding | StrategicFinding)[]> {
        this.setContext(context);
        if (this.healingPrompt) {
            const { findings } = await this.auditAndHeal();
            return findings;
        }
        const findings = await this.performAudit();
        return findings;
    }

    override getAuditRules(): { extensions: string[]; rules: AuditRule[] } {
        return {
            extensions: [".ts",".js"],
            rules: [
          {
                    "regex": "readFile[^(]*\\([^)]*(?!utf|encoding)[^)]*\\)",
                    "issue": "Risco i18n: Leitura de arquivo sem especificar encoding UTF-8.",
                    "severity": "medium"
          },
          {
                    "regex": "(?:message|label|title|text|placeholder)\\s*[:=]\\s*[\"'][A-Z][a-zÀ-ú]",
                    "issue": "Hardcoded String: Texto de interface diretamente no código — impede tradução.",
                    "severity": "medium"
          },
          {
                    "regex": "new\\s+Date\\(\\)\\.toLocaleDateString\\(\\)",
                    "issue": "Locale Implícito: toLocaleDateString() sem locale explícito.",
                    "severity": "low"
          }
]
        };
    }

    public override async performAudit(): Promise<AuditFinding[]> {
        this.startMetrics();
        
        const allFindings: AuditFinding[] = [];
        const files = Object.keys(this.contextData);
        
        for (const file of files) {
            const results = await this.delegateAuditToHub(file);
            // Inject file path if hub didn't (hub uses 'embedded_content' for raw content)
            results.forEach(f => {
                if (f.file === "embedded_content") f.file = file;
                allFindings.push(f);
            });
        }
        
        this.endMetrics(allFindings.length);
        return allFindings;
    }

    public override async reasonAboutObjective(objective: string, file: string, context: string): Promise<StrategicFinding | null> {
        return await super.reasonAboutObjective(objective, file, context);
    }

    override selfDiagnostic(): any {
        return { status: "Soberano", score: 100, details: "Módulo Globe operando com paridade total via Forge." };
    }

    override getSystemPrompt(): string {
        return `Você é o Dr. Globe, PhD em Internationalization & Localization (TypeScript). Sua missão é garantir a excelência via governança PhD.`;
    }
}
