import winston from "winston";
import type { IAgent, ProjectContext, AuditFinding, StrategicFinding, AuditRule } from "../../../core/types.ts";

const logger = winston.child({ module: "Warden" });

/**
 * 🛡️ Dr. Warden — PhD in Sovereignty & Strategic Security (TypeScript)
 * Generated by Sovereign Forge.
 */
export class WardenPersona implements IAgent {
    public readonly id: string = "warden";
    public readonly name: string = "Warden";
    public readonly emoji: string = "🛡️";
    public readonly role: string = "PhD Strategic Guardian";
    public readonly category: string = "Strategic";
    public readonly stack: string = "TypeScript";
    public readonly phd_identity: string = "Sovereignty & Strategic Security (TypeScript)";

    private projectRoot: string;
    private contextData: Record<string, any> = {};
    private hub: any = null;
    private auditStartTime: number = 0;

    constructor(projectRoot?: string) {
        this.projectRoot = projectRoot || process.cwd();
    }

    async execute(context: ProjectContext): Promise<(AuditFinding | StrategicFinding)[]> {
        this.contextData = context.map || {};
        this.hub = context.hub || null;
        return await this.performAudit();
    }

    getAuditRules(): { extensions: string[]; rules: AuditRule[] } {
        return {
            extensions: [".ts",".tsx",".mjs",".cjs"],
            rules: [
          {
                    "regex": "process\\.env",
                    "issue": "Segurança: Acesso a variáveis de ambiente; verifique segredos PhD.",
                    "severity": "medium"
          }
]
        };
    }

    public async performAudit(): Promise<AuditFinding[]> {
        this.startMetrics();
        
        const allFindings: AuditFinding[] = [];
        const files = Object.keys(this.contextData);
        
        for (const file of files) {
            const results = await this.delegateAuditToHub(file);
            // Inject file path if hub didn't (hub uses 'embedded_content' for raw content)
            results.forEach(f => {
                if (f.file === "embedded_content") f.file = file;
                allFindings.push(f);
            });
        }
        
        this.endMetrics(allFindings.length);
        return allFindings;
    }

    public async reasonAboutObjective(objective: string, file: string, context: string): Promise<StrategicFinding | null> {
        if (this.hub) {
            const prompt = `Persona: ${this.name}\nPhD Identity: ${this.phd_identity}\nObjective: ${objective}\nContext: ${context}`;
            const answer = await this.hub.reason(prompt);
            if (answer) {
                return {
                    file,
                    severity: "INFO",
                    issue: answer,
                    context: objective,
                    agent: this.id,
                    role: this.role,
                    emoji: this.emoji
                };
            }
        }
        return null;
    }

    private startMetrics(): void { this.auditStartTime = Date.now(); }

    private endMetrics(cnt: number): void {
        const duration = Date.now() - this.auditStartTime;
        logger.info(`${this.emoji} [${this.name}] Finalizado: ${cnt} pts (${duration}ms)`);
    }

    private async delegateAuditToHub(fileRelPath: string): Promise<AuditFinding[]> {
        if (!this.hub) return [];
        const content = this.contextData[fileRelPath]?.content || "";
        if (!content) return [];
        return await this.hub.analyzeCode(content, this.id, this.stack);
    }

    selfDiagnostic(): any {
        return { status: "Soberano", score: 100, details: "Módulo Warden operando com paridade total via Forge." };
    }

    getSystemPrompt(): string {
        return `Você é o Dr. Warden, PhD em Sovereignty & Strategic Security (TypeScript). Sua missão é garantir a excelência via governança PhD.`;
    }
}
