import { BaseActivePersona } from "../../base.ts";
import type { AuditRule, StrategicFinding, AuditFinding, ProjectContext } from "../../base.ts";

/**
 * 🏷️ Dr. Enum — PhD in Enum Safety & Discriminated Unions (TypeScript)
 * Generated by Sovereign Forge.
 */
export class EnumPersona extends BaseActivePersona {
    constructor(projectRoot: string | undefined = undefined) {
        super(projectRoot);
        this.id = "enum";
        this.name = "Enum";
        this.emoji = "🏷️";
        this.role = "PhD TypeScript Union & Enum Engineer";
        this.phd_identity = "Enum Safety & Discriminated Unions (TypeScript)";
        this.stack = "Bun";
        this.healingPrompt = "";
    }

    override async execute(context: ProjectContext): Promise<(AuditFinding | StrategicFinding)[]> {
        this.setContext(context);
        const findings = await this.performAudit();
        return findings;
    }

    override getAuditRules(): { extensions: string[]; rules: AuditRule[] } {
        return {
            extensions: [".ts",".js"],
            rules: [
          {
                    "regex": "enum\\s+\\w+\\s*\\{[^}]*\\d+",
                    "issue": "Risco: Enum numérico — use string enum ou union type para segurança PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "enum\\s+\\w+\\s*\\{",
                    "issue": "Revisar: Enum TypeScript — considere \"as const\" object or union type PhD.",
                    "severity": "low"
          },
          {
                    "regex": "as\\s+\\w+Enum|as\\s+\\w+\\.\\w+",
                    "issue": "Cast de Enum: Type assertion em enum pode aceitar valor inválido PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "const\\s+enum\\s+",
                    "issue": "Limitação: const enum não funciona com --isolatedModules (Bun/Vite) PhD.",
                    "severity": "high"
          }
]
        };
    }

    public override async performAudit(): Promise<AuditFinding[]> {
        this.startMetrics();
        
        const allFindings: AuditFinding[] = [];
        const files = Object.keys(this.contextData);
        
        for (const file of files) {
            const results = await this.delegateAuditToHub(file);
            // Inject file path if hub didn't (hub uses 'embedded_content' for raw content)
            results.forEach(f => {
                if (f.file === "embedded_content") f.file = file;
                allFindings.push(f);
            });
        }
        
        this.endMetrics(allFindings.length);
        return allFindings;
    }

    public override async reasonAboutObjective(objective: string, file: string, context: string): Promise<StrategicFinding | null> {
        return await super.reasonAboutObjective(objective, file, context);
    }

    override selfDiagnostic(): any {
        return { status: "Soberano", score: 100, details: "Módulo Enum operando com paridade total via Forge." };
    }

    override getSystemPrompt(): string {
        return `Você é o Dr. Enum, PhD em Enum Safety & Discriminated Unions (TypeScript). Sua missão é garantir a excelência via governança PhD.`;
    }
}
