import { BaseActivePersona } from "../../base.ts";
import type { AuditRule, StrategicFinding, AuditFinding, HealingResult, ProjectContext } from "../../base.ts";

/**
 * 🧠 Dr. Neural — PhD in AI Token Safety & Cost Management (TypeScript)
 * Generated by Sovereign Forge.
 */
export class NeuralPersona extends BaseActivePersona {
    constructor(projectRoot: string | undefined = undefined) {
        super(projectRoot);
        this.id = "neural";
        this.name = "Neural";
        this.emoji = "🧠";
        this.role = "PhD AI Safety & Token Engineer";
        this.phd_identity = "AI Token Safety & Cost Management (TypeScript)";
        this.stack = "Bun";
        this.healingPrompt = "Fix the following ML/AI integration issue. Correct model loading, preprocessing pipelines, and inference errors. Return ONLY the corrected code or a specific diff.";
    }

    override async execute(context: ProjectContext): Promise<(AuditFinding | StrategicFinding)[]> {
        this.setContext(context);
        if (this.healingPrompt) {
            const { findings } = await this.auditAndHeal();
            return findings;
        }
        const findings = await this.performAudit();
        return findings;
    }

    override getAuditRules(): { extensions: string[]; rules: AuditRule[] } {
        return {
            extensions: [".ts",".js"],
            rules: [
          {
                    "regex": "sk-[a-zA-Z0-9]{20,}",
                    "issue": "Crítico: Chave OpenAI exposta no código-fonte PhD.",
                    "severity": "critical"
          },
          {
                    "regex": "OPENAI_API_KEY\\s*[:=]\\s*[\"']",
                    "issue": "Vazamento: OPENAI_API_KEY hardcoded PhD.",
                    "severity": "critical"
          },
          {
                    "regex": "model\\s*[:=]\\s*[\"']gpt-4",
                    "issue": "Custo: Modelo GPT-4 sem limite de tokens — risco de custo descontrolado PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "max_tokens\\s*[:=]\\s*(?:undefined|null|0)",
                    "issue": "Sem Limite: Requisição à LLM sem max_tokens configurado PhD.",
                    "severity": "high"
          },
          {
                    "regex": "temperature\\s*[:=]\\s*(?:1\\.\\d|2)",
                    "issue": "Instabilidade: Temperature alta (>1.0) gera respostas imprevisíveis PhD.",
                    "severity": "low"
          }
]
        };
    }

    public override async performAudit(): Promise<AuditFinding[]> {
        this.startMetrics();
        
        const allFindings: AuditFinding[] = [];
        const files = Object.keys(this.contextData);
        
        for (const file of files) {
            const results = await this.delegateAuditToHub(file);
            // Inject file path if hub didn't (hub uses 'embedded_content' for raw content)
            results.forEach(f => {
                if (f.file === "embedded_content") f.file = file;
                allFindings.push(f);
            });
        }
        
        this.endMetrics(allFindings.length);
        return allFindings;
    }

    public override async reasonAboutObjective(objective: string, file: string, context: string): Promise<StrategicFinding | null> {
        return await super.reasonAboutObjective(objective, file, context);
    }

    override selfDiagnostic(): any {
        return { status: "Soberano", score: 100, details: "Módulo Neural operando com paridade total via Forge." };
    }

    override getSystemPrompt(): string {
        return `Você é o Dr. Neural, PhD em AI Token Safety & Cost Management (TypeScript). Sua missão é garantir a excelência via governança PhD.`;
    }
}
