from ..base import BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext
import re

class NeuralPersona(BaseActivePersona):
    """
    🧠 Dr. Neural — PhD in AI Token Safety & Cost Management (TypeScript)
    Generated by Sovereign Forge.
    """
    def __init__(self, project_root: str = None):
        super().__init__(project_root)
        self.id = "neural"
        self.name = "Neural"
        self.emoji = "🧠"
        self.role = "PhD AI Safety & Token Engineer"
        self.phd_identity = "AI Token Safety & Cost Management (TypeScript)"
        self.stack = "Python"
        self.healing_prompt = "Fix the following ML/AI integration issue. Correct model loading, preprocessing pipelines, and inference errors. Return ONLY the corrected code or a specific diff."

    async def execute(self, context: ProjectContext) -> list:
        self.set_context(context)
        return await self.perform_audit()

    def get_audit_rules(self) -> dict:
        return {
            "extensions": [".py"],
            "rules": [
                # [
          {
                    "regex": "sk-[a-zA-Z0-9]{20,}",
                    "issue": "Crítico: Chave OpenAI exposta no código-fonte PhD.",
                    "severity": "critical"
          },
          {
                    "regex": "OPENAI_API_KEY\\s*[:=]\\s*[\"']",
                    "issue": "Vazamento: OPENAI_API_KEY hardcoded PhD.",
                    "severity": "critical"
          },
          {
                    "regex": "model\\s*[:=]\\s*[\"']gpt-4",
                    "issue": "Custo: Modelo GPT-4 sem limite de tokens — risco de custo descontrolado PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "max_tokens\\s*[:=]\\s*(?:undefined|null|0)",
                    "issue": "Sem Limite: Requisição à LLM sem max_tokens configurado PhD.",
                    "severity": "high"
          },
          {
                    "regex": "temperature\\s*[:=]\\s*(?:1\\.\\d|2)",
                    "issue": "Instabilidade: Temperature alta (>1.0) gera respostas imprevisíveis PhD.",
                    "severity": "low"
          }
]
            ]
        }

    async def reason_about_objective(self, objective: str, file: str, context: str) -> dict:
        return {
            "file": file,
            "severity": "INFO",
            "issue": f"PhD Neural (Python): Analyzing {objective} in {file}.",
            "context": "analyzing objective"
        }

    async def delegate_healing_to_hub(self, file: str, issue: str) -> str:
        # Delegation logic here via gRPC back to Hub
        return None
