from ..base import BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext
import re

class SparkPersona(BaseActivePersona):
    """
    ✨ Dr. Spark — PhD in Developer Experience & UX Tooling (TypeScript)
    Generated by Sovereign Forge.
    """
    def __init__(self, project_root: str = None):
        super().__init__(project_root)
        self.id = "spark"
        self.name = "Spark"
        self.emoji = "✨"
        self.role = "PhD Developer Experience Engineer"
        self.phd_identity = "Developer Experience & UX Tooling (TypeScript)"
        self.stack = "Python"
        self.healing_prompt = "Fix the following build system or compilation issue. Correct build configurations, tree-shaking settings, and bundler errors. Return ONLY the corrected code or a specific diff."

    async def execute(self, context: ProjectContext) -> list:
        self.set_context(context)
        return await self.perform_audit()

    def get_audit_rules(self) -> dict:
        return {
            "extensions": [".py"],
            "rules": [
                # [
          {
                    "regex": "process\\.exit\\(\\d+\\)(?![\\s\\S]{0,30}console|log|error)",
                    "issue": "Saída Silenciosa: process.exit() sem aviso ao dev. Forneça contexto visível PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "throw\\s+new\\s+Error\\([\"'][\"']\\)",
                    "issue": "Erro Mudo: Error lançado com mensagem vazia PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "\\.on\\([\"']error[\"']\\s*,\\s*\\(\\)\\s*=>\\s*\\{\\s*\\}\\)",
                    "issue": "Erro Invisível: Event handler de erro vazio (engolido) PhD.",
                    "severity": "high"
          }
]
            ]
        }

    async def reason_about_objective(self, objective: str, file: str, context: str) -> dict:
        return {
            "file": file,
            "severity": "INFO",
            "issue": f"PhD Spark (Python): Analyzing {objective} in {file}.",
            "context": "analyzing objective"
        }

    async def delegate_healing_to_hub(self, file: str, issue: str) -> str:
        # Delegation logic here via gRPC back to Hub
        return None
