import 'package:personas_agentes/core/base.dart';

/**
 * 🛸 Dr. Voyager — PhD in Legacy Modernization & Future-Proofing (TypeScript)
 * Generated by Sovereign Forge.
 */
class VoyagerPersona extends BaseActivePersona {
  VoyagerPersona({String? projectRoot}) : super(projectRoot) {
    this.name = "Voyager";
    this.emoji = "🛸";
    this.role = "PhD Modernization Architect";
    this.    phdIdentity = "Legacy Modernization & Future-Proofing (TypeScript)",
    stack = "Flutter",
    healingPrompt = "";
  }

  @override
  Future<List<dynamic>> execute(ProjectContext context) async {
    this.setContext(context);
    return await this.performAudit();
  }

  @override
  Map<String, dynamic> getAuditRules() {
    return {
      'extensions': [".dart"],
      'rules': [
        // [
          {
                    "regex": "var\\s+",
                    "issue": "Legado: Uso de 'var' detectado. Use 'const' ou 'let' PhD.",
                    "severity": "high"
          },
          {
                    "regex": "module\\.exports",
                    "issue": "Legado: CommonJS detectado. Use ESM (export/import) PhD.",
                    "severity": "medium"
          }
]
      ],
    };
  }

  Future<void> performAudit() async {
    print("💙 [${name}] Starting fleet-wide audit via Hub PhD...");
    // delegation logic here using a gRPC client stub
  }

  void reasonAboutObjective(String objective, String file, String context) {
    print("💙 [${name}] Delegating reasoning for '${objective}' to Hub...");
  }

  void delegateHealingToHub(String file, String issue) {
    print("💙 [${name}] Delegating healing for '$issue' to Hub...");
  }
}
