from ..base import BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext
import re

class FragmentPersona(BaseActivePersona):
    """
    🧩 Dr. Fragment — PhD in Mdoularity & Structural Cohesion (TS/Bun)
    Generated by Sovereign Forge.
    """
    def __init__(self, project_root: str = None):
        super().__init__(project_root)
        self.id = "fragment"
        self.name = "Fragment"
        self.emoji = "🧩"
        self.role = "PhD Refactoring Expert"
        self.phd_identity = "Mdoularity & Structural Cohesion (TS/Bun)"
        self.stack = "Python"
        self.healing_prompt = "Fix the following component isolation or micro-frontend issue. Remove cross-boundary imports and enforce strict module isolation. Return ONLY the corrected code or a specific diff."

    async def execute(self, context: ProjectContext) -> list:
        self.set_context(context)
        return await self.perform_audit()

    def get_audit_rules(self) -> dict:
        return {
            "extensions": [".py"],
            "rules": [
                # [
          {
                    "regex": "import\\s+.*\\s+from\\s+['\"]\\.\\.\\/\\.\\.\\/\\.\\.\\/",
                    "issue": "Coupling: Importação profunda detectada. Considere usar alias de caminhos ou refatorar para pacotes mais próximos.",
                    "severity": "low"
          },
          {
                    "regex": "class\\s+\\w+\\s+\\{.*constructor\\(.*\\)\\s+\\{.*new\\s+\\w+.*\\}.*\\}",
                    "issue": "Dependency Injection: Instanciação direta no construtor. Use injeção de dependência para facilitar testabilidade PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "export\\s+default",
                    "issue": "Clarity: Prefira named exports para facilitar o rastreio de dependências e refatorações automatizadas.",
                    "severity": "low"
          },
          {
                    "regex": "any",
                    "issue": "Type Quality: Uso de 'any' detectado. Violação grave da integridade de tipos; prefira 'unknown' ou tipos específicos.",
                    "severity": "high"
          }
]
            ]
        }

    async def reason_about_objective(self, objective: str, file: str, context: str) -> dict:
        return {
            "file": file,
            "severity": "INFO",
            "issue": f"PhD Fragment (Python): Analyzing {objective} in {file}.",
            "context": "analyzing objective"
        }

    async def delegate_healing_to_hub(self, file: str, issue: str) -> str:
        # Delegation logic here via gRPC back to Hub
        return None
