from ..base import BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext
import re

class GlobePersona(BaseActivePersona):
    """
    🌍 Dr. Globe — PhD in Internationalization & Localization (TypeScript)
    Generated by Sovereign Forge.
    """
    def __init__(self, project_root: str = None):
        super().__init__(project_root)
        self.id = "globe"
        self.name = "Globe"
        self.emoji = "🌍"
        self.role = "PhD Internationalization Engineer"
        self.phd_identity = "Internationalization & Localization (TypeScript)"
        self.stack = "Python"
        self.healing_prompt = "Fix the following i18n or localization issue. Replace hardcoded strings with locale keys and ensure locale-aware formatting. Return ONLY the corrected code or a specific diff."

    async def execute(self, context: ProjectContext) -> list:
        self.set_context(context)
        return await self.perform_audit()

    def get_audit_rules(self) -> dict:
        return {
            "extensions": [".py"],
            "rules": [
                # [
          {
                    "regex": "readFile[^(]*\\([^)]*(?!utf|encoding)[^)]*\\)",
                    "issue": "Risco i18n: Leitura de arquivo sem especificar encoding UTF-8.",
                    "severity": "medium"
          },
          {
                    "regex": "(?:message|label|title|text|placeholder)\\s*[:=]\\s*[\"'][A-Z][a-zÀ-ú]",
                    "issue": "Hardcoded String: Texto de interface diretamente no código — impede tradução.",
                    "severity": "medium"
          },
          {
                    "regex": "new\\s+Date\\(\\)\\.toLocaleDateString\\(\\)",
                    "issue": "Locale Implícito: toLocaleDateString() sem locale explícito.",
                    "severity": "low"
          }
]
            ]
        }

    async def reason_about_objective(self, objective: str, file: str, context: str) -> dict:
        return {
            "file": file,
            "severity": "INFO",
            "issue": f"PhD Globe (Python): Analyzing {objective} in {file}.",
            "context": "analyzing objective"
        }

    async def delegate_healing_to_hub(self, file: str, issue: str) -> str:
        # Delegation logic here via gRPC back to Hub
        return None
