from ..base import BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext
import re

class HypePersona(BaseActivePersona):
    """
    🚀 Dr. Hype — PhD in Product Visibility & Branding (TypeScript)
    Generated by Sovereign Forge.
    """
    def __init__(self, project_root: str = None):
        super().__init__(project_root)
        self.id = "hype"
        self.name = "Hype"
        self.emoji = "🚀"
        self.role = "PhD Product Evangelist"
        self.phd_identity = "Product Visibility & Branding (TypeScript)"
        self.stack = "Python"
        self.healing_prompt = "Fix the following developer experience issue. Simplify confusing APIs, improve error messages, and streamline interfaces. Return ONLY the corrected code or a specific diff."

    async def execute(self, context: ProjectContext) -> list:
        self.set_context(context)
        return await self.perform_audit()

    def get_audit_rules(self) -> dict:
        return {
            "extensions": [".py"],
            "rules": [
                # [
          {
                    "regex": "\"description\":\\s*\"\"",
                    "issue": "Invisível: package.json sem campo \"description\".",
                    "severity": "medium"
          },
          {
                    "regex": "\"license\":\\s*\"\"",
                    "issue": "Risco Legal: package.json sem campo \"license\".",
                    "severity": "high"
          },
          {
                    "regex": "\"name\":\\s*\"(my-app|project|untitled|test|app)\"",
                    "issue": "Genérico: Nome de pacote genérico impede a identidade do projeto.",
                    "severity": "medium"
          }
]
            ]
        }

    async def reason_about_objective(self, objective: str, file: str, context: str) -> dict:
        return {
            "file": file,
            "severity": "INFO",
            "issue": f"PhD Hype (Python): Analyzing {objective} in {file}.",
            "context": "analyzing objective"
        }

    async def delegate_healing_to_hub(self, file: str, issue: str) -> str:
        # Delegation logic here via gRPC back to Hub
        return None
