// ─── Mappings ─────────────────────────────────────────────────────────────

export const LEGACY_ALIASES: Record<string, string> = {
    "reflex_engine_phd": "reflex_engine",
    "ast_navigator": "ast_intelligence",
    "ast_node_inspector": "ast_intelligence",
    "ast_traversal_logic": "ast_intelligence",
    "audit_risk_engine": "audit_expert_engine",
    "audit_scanner_engine": "audit_expert_engine",
    "safe_context_judge": "safety_supreme_judge",
    "safety_heuristics": "safety_supreme_judge",
    "safety_assignment_engine": "safety_supreme_judge",
    "safety_navigator": "safety_supreme_judge",
    "rule_definition_judge": "safety_supreme_judge",
    "obfuscation_cleaner_engine": "vulnerability_heuristic",
    "telemetry_intent_judge": "telemetry_excellence_engine",
    "telemetry_maturity_logic": "telemetry_excellence_engine",
    "intent_heuristics_engine": "telemetry_excellence_engine",
    "test_discovery_logic": "telemetry_excellence_engine",
    "analysis_engine_phd": "phd_governance_system",
    "conflict_policy_phd": "phd_governance_system",
    "scoring_engine_phd": "phd_governance_system",
    "topology_engine_phd": "phd_governance_system",
    "compliance_standard": "phd_governance_system",
    "git_operations_phd": "phd_governance_system",
    "veto_rules_phd": "phd_governance_system",
    "test_bolt": "specialized_personas_hub",
    "test_director": "specialized_personas_hub",
    "test_sentinel": "specialized_personas_hub",
    "test_vault": "specialized_personas_hub",
    "logic_node_auditor": "structural_auditor_supreme",
    "silent_error_detector": "structural_auditor_supreme",
    "semantic_context_analyst": "structural_auditor_supreme",
    "meta_analysis_detector": "structural_auditor_supreme",
    "call_safety_judge": "safety_supreme_judge",
    "code_inspector": "structural_auditor_supreme",
    "line_veto": "structural_auditor_supreme",
    "metrics_assembler": "structural_auditor_supreme",
    "registry_compiler": "audit_expert_engine",
    "report_sections_engine": "report_formatter",
    "test_navigator": "ast_intelligence",
    "veto_criteria_engine": "structural_auditor_supreme",
    "veto_rules": "structural_auditor_supreme",
    "veto_structural_engine": "structural_auditor_supreme",
    "web_insight": "discovery",
    "compiler": "phd_governance_system",
    "test_core_depth": "telemetry_excellence_engine",
    "test_score_calculator": "phd_governance_system",
    "indexer": "phd_governance_system",
    "parallel_test_executor": "telemetry_excellence_engine",
    "persona_loader": "phd_governance_system",
    "resource_governor": "phd_governance_system",
    "semantic_search": "discovery",
    "test_mapper": "telemetry_excellence_engine",
    "voice_engine": "briefing",
    "agents_registry": "audit_expert_engine"
};

export const FILE_MAPPINGS: Record<string, string> = {
    "git_automaton.py": "utils/git_client.ts",
    "markdown_sanitizer.py": "agents/Support/markdown_auditor.ts",
    "telemetry_intent_judge.py": "agents/Support/logic_auditor.ts",
    "telemetry_maturity_logic.py": "agents/Support/logic_auditor.ts",
    "silent_error_detector.py": "agents/Support/logic_auditor.ts",
    "meta_analysis_detector.py": "agents/Support/logic_auditor.ts",
    "call_safety_judge.py": "agents/Support/logic_auditor.ts",
    "safe_context_judge.py": "agents/Support/logic_auditor.ts",
    "resource_governor.py": "utils/system_sentinel.ts",
    "conflict_policy.py": "utils/conflict_policy.ts",
    "memory_pruning_agent.py": "utils/memory_pruning_agent.ts",
    "audit_risk_engine.py": "agents/Support/logic_auditor.ts",
    "audit_scanner_engine.py": "core/audit_engine.ts",
    "veto_criteria_engine.py": "utils/veto_engine.ts",
    "veto_rules.py": "utils/veto_engine.ts",
    "veto_structural_engine.py": "utils/veto_engine.ts",
    "safety_heuristics.py": "agents/Support/logic_auditor.ts",
    "safety_assignment_engine.py": "agents/Support/logic_auditor.ts",
    "report_formatter.py": "core/diagnostic_finalizer.ts",
    "report_sections_engine.py": "core/diagnostic_finalizer.ts"
};

export const IGNORE_LIST = [
    "ast_navigator.py",
    "ast_node_inspector.py",
    "ast_traversal_logic.py",
    "source_code_parser.py",
    "registry_compiler.py",
    "obfuscation_cleaner_engine.py",
    "logic_node_auditor.py"
];
