// ─── Mappings ─────────────────────────────────────────────────────────────

export const LEGACY_ALIASES: Record<string, string> = {
    "reflex_engine_phd": "reflex_engine",
    "ast_navigator": "ast_intelligence",
    "ast_node_inspector": "ast_intelligence",
    "ast_traversal_logic": "ast_intelligence",
    "audit_risk_engine": "audit_expert_engine",
    "audit_scanner_engine": "audit_expert_engine",
    "safe_context_judge": "safety_supreme_judge",
    "safety_heuristics": "safety_supreme_judge",
    "safety_assignment_engine": "safety_supreme_judge",
    "safety_navigator": "safety_supreme_judge",
    "rule_definition_judge": "safety_supreme_judge",
    "obfuscation_cleaner_engine": "vulnerability_heuristic",
    "telemetry_intent_judge": "telemetry_excellence_engine",
    "telemetry_maturity_logic": "telemetry_excellence_engine",
    "intent_heuristics_engine": "telemetry_excellence_engine",
    "test_discovery_logic": "telemetry_excellence_engine",
    "analysis_engine_phd": "phd_governance_system",
    "conflict_policy_phd": "phd_governance_system",
    "scoring_engine_phd": "phd_governance_system",
    "topology_engine_phd": "phd_governance_system",
    "compliance_standard": "phd_governance_system",
    "git_operations_phd": "phd_governance_system",
    "veto_rules_phd": "phd_governance_system",
    "test_bolt": "specialized_personas_hub",
    "test_director": "specialized_personas_hub",
    "test_sentinel": "specialized_personas_hub",
    "test_vault": "specialized_personas_hub",
    "logic_node_auditor": "structural_auditor_supreme",
    "silent_error_detector": "structural_auditor_supreme",
    "semantic_context_analyst": "structural_auditor_supreme",
    "meta_analysis_detector": "structural_auditor_supreme",
    "call_safety_judge": "safety_supreme_judge",
    "code_inspector": "structural_auditor_supreme",
    "line_veto": "structural_auditor_supreme",
    "metrics_assembler": "structural_auditor_supreme",
    "registry_compiler": "audit_expert_engine",
    "report_sections_engine": "report_formatter",
    "test_navigator": "ast_intelligence",
    "veto_criteria_engine": "structural_auditor_supreme",
    "veto_rules": "structural_auditor_supreme",
    "veto_structural_engine": "structural_auditor_supreme",
    "web_insight": "discovery",
    "compiler": "phd_governance_system",
    "test_core_depth": "telemetry_excellence_engine",
    "test_score_calculator": "phd_governance_system",
    "indexer": "phd_governance_system",
    "parallel_test_executor": "telemetry_excellence_engine",
    "persona_loader": "phd_governance_system",
    "resource_governor": "phd_governance_system",
    "semantic_search": "discovery",
    "test_mapper": "telemetry_excellence_engine",
    "voice_engine": "briefing",
    "agents_registry": "audit_expert_engine"
};

export const FILE_MAPPINGS: Record<string, string> = {
    "git_automaton.py": "utils/git_client.ts",
    "markdown_sanitizer.py": "agents/Support/markdown_auditor.ts",
    "telemetry_intent_judge.py": "agents/Support/logic_auditor.ts",
    "telemetry_maturity_logic.py": "agents/Support/logic_auditor.ts",
    "silent_error_detector.py": "agents/Support/logic_auditor.ts",
    "meta_analysis_detector.py": "agents/Support/logic_auditor.ts",
    "call_safety_judge.py": "agents/Support/logic_auditor.ts",
    "safe_context_judge.py": "agents/Support/logic_auditor.ts",
    "resource_governor.py": "utils/system_sentinel.ts",
    "conflict_policy.py": "utils/conflict_policy.ts",
    "memory_pruning_agent.py": "utils/memory_pruning_agent.ts",
    "audit_risk_engine.py": "agents/Support/logic_auditor.ts",
    "audit_scanner_engine.py": "core/audit_engine.ts",
    "veto_criteria_engine.py": "utils/veto_engine.ts",
    "veto_rules.py": "utils/veto_engine.ts",
    "veto_structural_engine.py": "utils/veto_engine.ts",
    "safety_heuristics.py": "agents/Support/logic_auditor.ts",
    "safety_assignment_engine.py": "agents/Support/logic_auditor.ts",
    "report_formatter.py": "core/diagnostic_finalizer.ts",
    "report_sections_engine.py": "core/diagnostic_finalizer.ts"
};

export const IGNORE_LIST = [
    "ast_navigator.py",
    "ast_node_inspector.py",
    "ast_traversal_logic.py",
    "source_code_parser.py",
    "registry_compiler.py",
    "obfuscation_cleaner_engine.py",
    "logic_node_auditor.py",
    "6dec891_parallel_test.py",
    "6dec891_main_gui.py",
    "6dec891_gui.py",
    "chat_view_legacy.py",
    "cli_legacy.py",
    "dashboard_legacy.py",
    "dashboard_view_legacy.py",
    "cognitive_engine_legacy.py",
    "cognitive_engine_legacy_v2.py",
    "gui_native_legacy.py",
    "health_gauge_legacy.py",
    "pyramid_analyst_legacy.py",
    "main_gui.py",
    "restored_maintenance_engine_phd.py",
    "gui_legacy.py",
    "quality_analyst_legacy.py",
    "tray_legacy.py",
    "ui_controller_legacy.py",
    "test_runner_legacy.py",
    "shadow_tray_legacy.py",
    "benchmark_tests.py",
    "analyze_external.py",
    "build_exe.py",
    "cleanup_obfuscation.py",
    "debug_test_hang.py",
    "diagnose_blind_spots.py",
    "fast_diagnostic.py",
    "generate_tests.py",
    "install_hooks.py",
    "git_doctor.py",
    "launch_api.py",
    "lint_heading_logic.py",
    "lint_rule_engine.py",
    "persona_manager.py",
    "launch_dashboard.py",
    "run_diagnostic.py",
    "update_agent_submodule.py",
    "verify_cognitive.py",
    "shadow_tray.py",
    "verify_report_lint.py",
    "doc_gen_agent.py",
    "semantic_search_agent.py",
    "voice_engine.py",
    "test_mapper.py",
    "history_agent.py",
    "findings_view.py",
    "gui_native.py",
    "chat_view.py",
    "test_web_insight.py",
    "test_ai_infra.py",
    "src_local/agents/Support/doc_gen_agent.py",
    "test_analysis_engine_phd.py",
    "test_analyze_external.py",
    "test_ast_navigator.py",
    "test_ast_node_inspector.py",
    "test_ast_traversal_logic.py",
    "test_audit_engine.py",
    "test_audit_risk_engine.py",
    "test_audit_scanner_engine.py",
    "test_base_deep.py",
    "test_battle_plan_formatter_deep.py",
    "test_battle_plan_sections_engine.py",
    "test_bolt_persona.py",
    "test_bolt.py",
    "test_bridge.py",
    "test_briefing_agent.py",
    "test_cache_manager_system.py",
    "test_cache_manager.py",
    "test_cache.py",
    "test_call_safety_judge.py",
    "test_cleanup_obfuscation.py",
    "test_cli_system.py",
    "test_cli.py",
    "test_code_inspector_agent.py",
    "test_cognitive_analyst.py",
    "test_cognitive_engine.py",
    "test_compiler.py",
    "test_compliance_standard.py",
    "test_compliance.py",
    "test_component_classifier_deep.py",
    "test_components_smoke.py",
    "test_conflict_policy_phd.py",
    "test_connectivity_mapper.py",
    "test_context_engine_deep.py",
    "test_context_engine_system.py",
    "test_context_iterator.py",
    "test_context_mapping_logic.py",
    "test_context_sovereignty.py",
    "test_core_depth.py",
    "test_coverage_auditor.py",
    "test_dashboard_view.py",
    "test_debug_relevance.py",
    "test_delegation_engines.py",
    "test_dependency_auditor_deep.py",
    "test_dependency_auditor_system.py",
    "test_diagnose_blind_spots.py",
    "test_diagnostic_finalizer.py",
    "test_diagnostic_pipeline.py",
    "test_diagnostic_strategist.py",
    "test_director_persona.py",
    "test_director_system.py",
    "test_discovery_agent.py",
    "test_dna_profiler.py",
    "test_echo.py",
    "test_file_system_scanner.py",
    "test_final_check.py",
    "test_finding_deduplicator.py",
    "test_flow.py",
    "test_flutter_sentinel.py",
    "test_flutter_vault.py",
    "test_forge.py",
    "test_git_automaton.py",
    "test_git_client.py",
    "test_git_doctor.py",
    "test_git_logic.py",
    "test_git_operations_phd.py",
    "test_globe.py",
    "test_healer.py",
    "test_health_gauge.py",
    "test_health_synthesizer_deep.py",
    "test_hermes.py",
    "test_history_agent.py",
    "test_hype.py",
    "test_indexer_system.py",
    "test_indexer.py",
    "test_infrastructure_assembler.py",
    "test_install_hooks.py",
    "test_integrity_guardian.py",
    "test_intent_heuristics_engine.py",
    "test_kotlin_flow.py",
    "test_kotlin_hermes.py",
    "test_kotlin_sentinel.py",
    "test_launch_api.py",
    "test_launch_dashboard.py",
    "test_line_veto_deep.py",
    "test_lint_engines.py",
    "test_lint_heading_logic.py",
    "test_lint_rule_engine.py",
    "test_logging_config.py",
    "test_logic_auditor_deep.py",
    "test_logic_node_auditor.py",
    "test_maintenance_engine_phd.py",
    "test_mantra.py",
    "test_markdown_processor.py",
    "test_markdown_sanitizer.py",
    "test_markdown_structure_agent.py",
    "test_markdown_util.py",
    "test_maturity_evaluator.py",
    "test_memory_engine.py",
    "test_memory_persistence.py",
    "test_memory_pruning_agent.py",
    "test_memory_pruning.py",
    "test_meta_analysis_detector.py",
    "test_metric.py",
    "test_metrics_assembler.py",
    "test_nebula.py",
    "test_neural.py",
    "test_nexus.py",
    "test_obfuscation_cleaner_engine.py",
    "test_obfuscation_hunter.py",
    "test_obfuscation_logic_engine.py",
    "test_ontology.py",
    "test_orchestrator.py",
    "test_package_integrity.py",
    "test_palette.py",
    "test_parity_analyst.py",
    "test_penalty_engine.py",
    "test_persona_loader.py",
    "test_persona_manager.py",
    "test_phd_helpers.py",
    "test_probe.py",
    "test_pyramid_analyst.py",
    "test_python_personas.py",
    "test_quality_analyst.py",
    "test_reflex_engine_phd.py",
    "test_registry_compiler.py",
    "test_report_formatter.py",
    "test_report_sections_engine.py",
    "test_resource_governor.py",
    "test_rule_definition_judge.py",
    "test_run_diagnostic.py",
    "test_safe_context_judge.py",
    "test_safety_assignment_engine.py",
    "test_safety_definitions.py",
    "test_safety_heuristics.py",
    "test_safety_navigator.py",
    "test_scale.py",
    "test_scope.py",
    "test_score_calculator.py",
    "test_scoring_engine_phd.py",
    "test_scoring_metrics_engine.py",
    "test_scribe.py",
    "test_security_sentinel_agent.py",
    "test_security_sentinel.py",
    "test_self_awareness.py",
    "test_semantic_context_analyst.py",
    "test_sentinel_persona.py",
    "test_sentinel.py",
    "test_shadow_tray.py",
    "test_sidebar.py",
    "test_silent_error_detector.py",
    "test_source_code_parser_deep.py",
    "test_source_code_parser.py",
    "test_sovereign_sync_forensics.py",
    "test_spark.py",
    "test_stability_ledger_deep.py",
    "test_stream.py",
    "test_structural_analyst_deep.py",
    "test_structural_analyst.py",
    "test_submodule_sync_logic.py",
    "test_support_complexity_fix.py",
    "test_sync_engine_mocks.py",
    "test_system_health.py",
    "test_system_intelligence.py",
    "test_task_executor.py",
    "test_task_orchestrator.py",
    "test_telemetry_intent_judge.py",
    "test_telemetry_maturity_logic.py",
    "test_test_discovery_logic.py",
    "test_test_navigator.py",
    "test_test_runner.py",
    "test_testify.py",
    "test_topology_engine_phd.py",
    "test_topology_graph_agent.py",
    "test_ui_controller.py",
    "test_update_agent_submodule.py",
    "test_update_transaction.py",
    "test_utils_engines.py",
    "test_utils_interface.py",
    "test_validation_agent.py",
    "test_validator_deep.py",
    "test_validator.py",
    "test_vault_persona.py",
    "test_vault.py",
    "test_verify_cognitive.py",
    "test_verify_report_lint.py",
    "test_veto_criteria_engine.py",
    "test_veto_rules_phd.py",
    "test_veto_structural_engine.py",
    "test_voyager.py",
    "test_vulnerability_heuristic_deep.py",
    "test_warden.py",
    "test_web_insight_agent.py"
];
