import 'package:personas_agentes/core/base.dart';

/**
 * ✨ Dr. Spark — PhD in Developer Experience & UX Tooling (TypeScript)
 * Generated by Sovereign Forge.
 */
class SparkPersona extends BaseActivePersona {
  SparkPersona({String? projectRoot}) : super(projectRoot) {
    this.name = "Spark";
    this.emoji = "✨";
    this.role = "PhD Developer Experience Engineer";
    this.    phdIdentity = "Developer Experience & UX Tooling (TypeScript)",
    stack = "Flutter",
    healingPrompt = "";
  }

  @override
  Future<List<dynamic>> execute(ProjectContext context) async {
    this.setContext(context);
    return await this.performAudit();
  }

  @override
  Map<String, dynamic> getAuditRules() {
    return {
      'extensions': [".dart"],
      'rules': [
        // [
          {
                    "regex": "process\\.exit\\(\\d+\\)(?![\\s\\S]{0,30}console|log|error)",
                    "issue": "Saída Silenciosa: process.exit() sem aviso ao dev. Forneça contexto visível PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "throw\\s+new\\s+Error\\([\"'][\"']\\)",
                    "issue": "Erro Mudo: Error lançado com mensagem vazia PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "\\.on\\([\"']error[\"']\\s*,\\s*\\(\\)\\s*=>\\s*\\{\\s*\\}\\)",
                    "issue": "Erro Invisível: Event handler de erro vazio (engolido) PhD.",
                    "severity": "high"
          }
]
      ],
    };
  }

  Future<void> performAudit() async {
    print("💙 [${name}] Starting fleet-wide audit via Hub PhD...");
    // delegation logic here using a gRPC client stub
  }

  void reasonAboutObjective(String objective, String file, String context) {
    print("💙 [${name}] Delegating reasoning for '${objective}' to Hub...");
  }

  void delegateHealingToHub(String file, String issue) {
    print("💙 [${name}] Delegating healing for '$issue' to Hub...");
  }
}
