package content

import (
	"context"
	"fmt"
	base "github.com/joaomagdaleno/Personas_Agentes/src_local/agents/Go"
)

/**
 * 🌍 Dr. Globe — PhD in Internationalization & Localization (TypeScript)
 * Generated by Sovereign Forge.
 */
type GlobePersona struct {
	base.BasePersona
}

func NewGlobePersona() *GlobePersona {
	return &GlobePersona{
		BasePersona: base.BasePersona{
			ID:    "globe",
			Name:  "Globe",
			Emoji: "🌍",
			Role:          "PhD Internationalization Engineer",
			Stack:         "Go",
			HealingPrompt: "Fix the following i18n or localization issue. Replace hardcoded strings with locale keys and ensure locale-aware formatting. Return ONLY the corrected code or a specific diff.",
		},
	}
}

// Execute performs the agent logic, delegating to the Hub PhD RuleProvider.
func (p *GlobePersona) Execute(ctx context.Context) {
	fmt.Printf("👷 [Globe] Starting fleet-wide audit via Hub PhD...\n")
	// delegation logic via gRPC
}

func (p *GlobePersona) ReasonAboutObjective(objective string, file string, context string) {
	fmt.Printf("👷 [Globe] Delegating reasoning for '%s' to Hub...\n", objective)
	// delegation logic via gRPC
}

func (p *GlobePersona) DelegateHealingToHub(file string, issue string) {
	fmt.Printf("👷 [Globe] Delegating healing for '%s' in '%s' to Hub...\n", issue, file)
	// delegation logic via gRPC
}
