// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "hub.proto" (package "hub", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message hub.RuleRequest
 */
export interface RuleRequest {
    /**
     * @generated from protobuf field: string persona_id = 1
     */
    personaId: string;
    /**
     * @generated from protobuf field: string stack = 2
     */
    stack: string;
}
/**
 * @generated from protobuf message hub.Rule
 */
export interface Rule {
    /**
     * @generated from protobuf field: string regex = 1
     */
    regex: string;
    /**
     * @generated from protobuf field: string issue = 2
     */
    issue: string;
    /**
     * @generated from protobuf field: string severity = 3
     */
    severity: string;
    /**
     * @generated from protobuf field: string scm_query = 4
     */
    scmQuery: string;
}
/**
 * @generated from protobuf message hub.RuleResponse
 */
export interface RuleResponse {
    /**
     * @generated from protobuf field: repeated hub.Rule rules = 1
     */
    rules: Rule[];
    /**
     * @generated from protobuf field: repeated string extensions = 2
     */
    extensions: string[];
    /**
     * @generated from protobuf field: string system_prompt = 3
     */
    systemPrompt: string;
    /**
     * @generated from protobuf field: string prompt_template = 4
     */
    promptTemplate: string;
}
/**
 * @generated from protobuf message hub.AnalyzeCodeRequest
 */
export interface AnalyzeCodeRequest {
    /**
     * @generated from protobuf field: string content = 1
     */
    content: string;
    /**
     * @generated from protobuf field: string persona_id = 2
     */
    personaId: string;
    /**
     * @generated from protobuf field: string stack = 3
     */
    stack: string;
}
/**
 * @generated from protobuf message hub.Empty
 */
export interface Empty {
}
/**
 * @generated from protobuf message hub.StatusResponse
 */
export interface StatusResponse {
    /**
     * @generated from protobuf field: string status = 1
     */
    status: string;
    /**
     * @generated from protobuf field: string version = 2
     */
    version: string;
    /**
     * @generated from protobuf field: hub.HealthUpdate health = 3
     */
    health?: HealthUpdate;
}
/**
 * @generated from protobuf message hub.HealthUpdate
 */
export interface HealthUpdate {
    /**
     * @generated from protobuf field: double cpu_usage = 1
     */
    cpuUsage: number;
    /**
     * @generated from protobuf field: double memory_usage = 2
     */
    memoryUsage: number;
    /**
     * @generated from protobuf field: int32 goroutines = 3
     */
    goroutines: number;
    /**
     * @generated from protobuf field: repeated hub.ProcessInfo heavy_processes = 4
     */
    heavyProcesses: ProcessInfo[];
    /**
     * @generated from protobuf field: string timestamp = 5
     */
    timestamp: string;
}
/**
 * @generated from protobuf message hub.ProcessInfo
 */
export interface ProcessInfo {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: int32 pid = 2
     */
    pid: number;
    /**
     * @generated from protobuf field: double mem_mb = 3
     */
    memMb: number;
    /**
     * @generated from protobuf field: double cpu_percent = 4
     */
    cpuPercent: number;
}
/**
 * @generated from protobuf message hub.Event
 */
export interface Event {
    /**
     * @generated from protobuf field: string type = 1
     */
    type: string; // "FILE_WRITE", "FILE_CREATE", "FILE_REMOVE", "HEALTH_ALERT"    /**
     * @generated from protobuf field: string path = 2
     */
    path: string;
    /**
     * @generated from protobuf field: string data = 3
     */
    data: string;
}
/**
 * @generated from protobuf message hub.ScanRequest
 */
export interface ScanRequest {
    /**
     * @generated from protobuf field: string directory = 1
     */
    directory: string;
    /**
     * @generated from protobuf field: string root = 2
     */
    root: string;
}
/**
 * @generated from protobuf message hub.FileMetadata
 */
export interface FileMetadata {
    /**
     * @generated from protobuf field: string path = 1
     */
    path: string;
    /**
     * @generated from protobuf field: int32 loc = 2
     */
    loc: number;
    /**
     * @generated from protobuf field: int32 sloc = 3
     */
    sloc: number;
    /**
     * @generated from protobuf field: int32 comments = 4
     */
    comments: number;
    /**
     * @generated from protobuf field: string intent = 5
     */
    intent: string;
}
/**
 * @generated from protobuf message hub.ScanResponse
 */
export interface ScanResponse {
    /**
     * @generated from protobuf field: repeated hub.FileMetadata files = 1
     */
    files: FileMetadata[];
}
/**
 * @generated from protobuf message hub.AnalyzeRequest
 */
export interface AnalyzeRequest {
    /**
     * @generated from protobuf field: string file = 1
     */
    file: string;
    /**
     * @generated from protobuf field: string content = 2
     */
    content: string; // Optional raw content to bypass disk I/O}
/**
 * @generated from protobuf message hub.AnalyzeResponse
 */
export interface AnalyzeResponse {
    /**
     * @generated from protobuf field: string json_data = 1
     */
    jsonData: string; // Full analysis from Rust as JSON string}
/**
 * @generated from protobuf message hub.TaskRequest
 */
export interface TaskRequest {
    /**
     * @generated from protobuf field: string task_type = 1
     */
    taskType: string;
    /**
     * @generated from protobuf field: string target_file = 2
     */
    targetFile: string;
}
/**
 * @generated from protobuf message hub.TaskResponse
 */
export interface TaskResponse {
    /**
     * @generated from protobuf field: int32 task_id = 1
     */
    taskId: number;
    /**
     * @generated from protobuf field: bool success = 2
     */
    success: boolean;
}
/**
 * @generated from protobuf message hub.PendingRequest
 */
export interface PendingRequest {
    /**
     * @generated from protobuf field: int32 limit = 1
     */
    limit: number;
}
/**
 * @generated from protobuf message hub.Task
 */
export interface Task {
    /**
     * @generated from protobuf field: int32 id = 1
     */
    id: number;
    /**
     * @generated from protobuf field: string task_type = 2
     */
    taskType: string;
    /**
     * @generated from protobuf field: string target_file = 3
     */
    targetFile: string;
    /**
     * @generated from protobuf field: string status = 4
     */
    status: string;
    /**
     * @generated from protobuf field: string result = 5
     */
    result: string;
    /**
     * @generated from protobuf field: string created_at = 6
     */
    createdAt: string;
}
/**
 * @generated from protobuf message hub.PendingResponse
 */
export interface PendingResponse {
    /**
     * @generated from protobuf field: repeated hub.Task tasks = 1
     */
    tasks: Task[];
}
/**
 * @generated from protobuf message hub.UpdateTaskRequest
 */
export interface UpdateTaskRequest {
    /**
     * @generated from protobuf field: int32 task_id = 1
     */
    taskId: number;
    /**
     * @generated from protobuf field: string status = 2
     */
    status: string;
    /**
     * @generated from protobuf field: string result = 3
     */
    result: string;
}
/**
 * @generated from protobuf message hub.DeduplicateRequest
 */
export interface DeduplicateRequest {
    /**
     * @generated from protobuf field: string findings_json = 1
     */
    findingsJson: string;
}
/**
 * @generated from protobuf message hub.ConnectivityRequest
 */
export interface ConnectivityRequest {
    /**
     * @generated from protobuf field: string dependency_map_json = 1
     */
    dependencyMapJson: string;
}
/**
 * @generated from protobuf message hub.AuditRequest
 */
export interface AuditRequest {
    /**
     * @generated from protobuf field: string audit_json = 1
     */
    auditJson: string;
}
/**
 * @generated from protobuf message hub.BatchRequest
 */
export interface BatchRequest {
    /**
     * @generated from protobuf field: string batch_json = 1
     */
    batchJson: string;
}
/**
 * @generated from protobuf message hub.ReasonRequest
 */
export interface ReasonRequest {
    /**
     * @generated from protobuf field: string prompt = 1
     */
    prompt: string;
    /**
     * @generated from protobuf field: bool use_rag = 2
     */
    useRag: boolean;
}
/**
 * @generated from protobuf message hub.PatternRequest
 */
export interface PatternRequest {
    /**
     * @generated from protobuf field: string pattern_json = 1
     */
    patternJson: string;
}
/**
 * @generated from protobuf message hub.PenaltyRequest
 */
export interface PenaltyRequest {
    /**
     * @generated from protobuf field: string penalty_json = 1
     */
    penaltyJson: string;
}
/**
 * @generated from protobuf message hub.ScoreRequest
 */
export interface ScoreRequest {
    /**
     * @generated from protobuf field: string score_json = 1
     */
    scoreJson: string;
}
/**
 * @generated from protobuf message hub.CoverageRequest
 */
export interface CoverageRequest {
    /**
     * @generated from protobuf field: string coverage_json = 1
     */
    coverageJson: string;
}
/**
 * @generated from protobuf message hub.GraphRequest
 */
export interface GraphRequest {
    /**
     * @generated from protobuf field: string graph_json = 1
     */
    graphJson: string;
}
/**
 * @generated from protobuf message hub.QueryRequest
 */
export interface QueryRequest {
    /**
     * @generated from protobuf field: string query_json = 1
     */
    queryJson: string;
}
/**
 * @generated from protobuf message hub.HealingPlan
 */
export interface HealingPlan {
    /**
     * @generated from protobuf field: string issue_description = 1
     */
    issueDescription: string;
    /**
     * @generated from protobuf field: string file_path = 2
     */
    filePath: string;
    /**
     * @generated from protobuf field: string file_content = 3
     */
    fileContent: string;
    /**
     * @generated from protobuf field: string context = 4
     */
    context: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class RuleRequest$Type extends MessageType<RuleRequest> {
    constructor() {
        super("hub.RuleRequest", [
            { no: 1, name: "persona_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "stack", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RuleRequest>): RuleRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.personaId = "";
        message.stack = "";
        if (value !== undefined)
            reflectionMergePartial<RuleRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RuleRequest): RuleRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string persona_id */ 1:
                    message.personaId = reader.string();
                    break;
                case /* string stack */ 2:
                    message.stack = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RuleRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string persona_id = 1; */
        if (message.personaId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.personaId);
        /* string stack = 2; */
        if (message.stack !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.stack);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.RuleRequest
 */
export const RuleRequest = new RuleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Rule$Type extends MessageType<Rule> {
    constructor() {
        super("hub.Rule", [
            { no: 1, name: "regex", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "issue", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "severity", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "scm_query", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Rule>): Rule {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.regex = "";
        message.issue = "";
        message.severity = "";
        message.scmQuery = "";
        if (value !== undefined)
            reflectionMergePartial<Rule>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Rule): Rule {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string regex */ 1:
                    message.regex = reader.string();
                    break;
                case /* string issue */ 2:
                    message.issue = reader.string();
                    break;
                case /* string severity */ 3:
                    message.severity = reader.string();
                    break;
                case /* string scm_query */ 4:
                    message.scmQuery = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Rule, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string regex = 1; */
        if (message.regex !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.regex);
        /* string issue = 2; */
        if (message.issue !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.issue);
        /* string severity = 3; */
        if (message.severity !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.severity);
        /* string scm_query = 4; */
        if (message.scmQuery !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.scmQuery);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.Rule
 */
export const Rule = new Rule$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RuleResponse$Type extends MessageType<RuleResponse> {
    constructor() {
        super("hub.RuleResponse", [
            { no: 1, name: "rules", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Rule },
            { no: 2, name: "extensions", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "system_prompt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "prompt_template", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RuleResponse>): RuleResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rules = [];
        message.extensions = [];
        message.systemPrompt = "";
        message.promptTemplate = "";
        if (value !== undefined)
            reflectionMergePartial<RuleResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RuleResponse): RuleResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated hub.Rule rules */ 1:
                    message.rules.push(Rule.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated string extensions */ 2:
                    message.extensions.push(reader.string());
                    break;
                case /* string system_prompt */ 3:
                    message.systemPrompt = reader.string();
                    break;
                case /* string prompt_template */ 4:
                    message.promptTemplate = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RuleResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated hub.Rule rules = 1; */
        for (let i = 0; i < message.rules.length; i++)
            Rule.internalBinaryWrite(message.rules[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated string extensions = 2; */
        for (let i = 0; i < message.extensions.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.extensions[i]);
        /* string system_prompt = 3; */
        if (message.systemPrompt !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.systemPrompt);
        /* string prompt_template = 4; */
        if (message.promptTemplate !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.promptTemplate);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.RuleResponse
 */
export const RuleResponse = new RuleResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AnalyzeCodeRequest$Type extends MessageType<AnalyzeCodeRequest> {
    constructor() {
        super("hub.AnalyzeCodeRequest", [
            { no: 1, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "persona_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "stack", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AnalyzeCodeRequest>): AnalyzeCodeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.content = "";
        message.personaId = "";
        message.stack = "";
        if (value !== undefined)
            reflectionMergePartial<AnalyzeCodeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AnalyzeCodeRequest): AnalyzeCodeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string content */ 1:
                    message.content = reader.string();
                    break;
                case /* string persona_id */ 2:
                    message.personaId = reader.string();
                    break;
                case /* string stack */ 3:
                    message.stack = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AnalyzeCodeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string content = 1; */
        if (message.content !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.content);
        /* string persona_id = 2; */
        if (message.personaId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.personaId);
        /* string stack = 3; */
        if (message.stack !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.stack);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.AnalyzeCodeRequest
 */
export const AnalyzeCodeRequest = new AnalyzeCodeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Empty$Type extends MessageType<Empty> {
    constructor() {
        super("hub.Empty", []);
    }
    create(value?: PartialMessage<Empty>): Empty {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<Empty>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Empty): Empty {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Empty, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.Empty
 */
export const Empty = new Empty$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StatusResponse$Type extends MessageType<StatusResponse> {
    constructor() {
        super("hub.StatusResponse", [
            { no: 1, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "health", kind: "message", T: () => HealthUpdate }
        ]);
    }
    create(value?: PartialMessage<StatusResponse>): StatusResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.status = "";
        message.version = "";
        if (value !== undefined)
            reflectionMergePartial<StatusResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StatusResponse): StatusResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string status */ 1:
                    message.status = reader.string();
                    break;
                case /* string version */ 2:
                    message.version = reader.string();
                    break;
                case /* hub.HealthUpdate health */ 3:
                    message.health = HealthUpdate.internalBinaryRead(reader, reader.uint32(), options, message.health);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StatusResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string status = 1; */
        if (message.status !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.status);
        /* string version = 2; */
        if (message.version !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.version);
        /* hub.HealthUpdate health = 3; */
        if (message.health)
            HealthUpdate.internalBinaryWrite(message.health, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.StatusResponse
 */
export const StatusResponse = new StatusResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HealthUpdate$Type extends MessageType<HealthUpdate> {
    constructor() {
        super("hub.HealthUpdate", [
            { no: 1, name: "cpu_usage", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "memory_usage", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "goroutines", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "heavy_processes", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ProcessInfo },
            { no: 5, name: "timestamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<HealthUpdate>): HealthUpdate {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cpuUsage = 0;
        message.memoryUsage = 0;
        message.goroutines = 0;
        message.heavyProcesses = [];
        message.timestamp = "";
        if (value !== undefined)
            reflectionMergePartial<HealthUpdate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HealthUpdate): HealthUpdate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double cpu_usage */ 1:
                    message.cpuUsage = reader.double();
                    break;
                case /* double memory_usage */ 2:
                    message.memoryUsage = reader.double();
                    break;
                case /* int32 goroutines */ 3:
                    message.goroutines = reader.int32();
                    break;
                case /* repeated hub.ProcessInfo heavy_processes */ 4:
                    message.heavyProcesses.push(ProcessInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string timestamp */ 5:
                    message.timestamp = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HealthUpdate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double cpu_usage = 1; */
        if (message.cpuUsage !== 0)
            writer.tag(1, WireType.Bit64).double(message.cpuUsage);
        /* double memory_usage = 2; */
        if (message.memoryUsage !== 0)
            writer.tag(2, WireType.Bit64).double(message.memoryUsage);
        /* int32 goroutines = 3; */
        if (message.goroutines !== 0)
            writer.tag(3, WireType.Varint).int32(message.goroutines);
        /* repeated hub.ProcessInfo heavy_processes = 4; */
        for (let i = 0; i < message.heavyProcesses.length; i++)
            ProcessInfo.internalBinaryWrite(message.heavyProcesses[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string timestamp = 5; */
        if (message.timestamp !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.HealthUpdate
 */
export const HealthUpdate = new HealthUpdate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProcessInfo$Type extends MessageType<ProcessInfo> {
    constructor() {
        super("hub.ProcessInfo", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "pid", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "mem_mb", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "cpu_percent", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<ProcessInfo>): ProcessInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.pid = 0;
        message.memMb = 0;
        message.cpuPercent = 0;
        if (value !== undefined)
            reflectionMergePartial<ProcessInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProcessInfo): ProcessInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* int32 pid */ 2:
                    message.pid = reader.int32();
                    break;
                case /* double mem_mb */ 3:
                    message.memMb = reader.double();
                    break;
                case /* double cpu_percent */ 4:
                    message.cpuPercent = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProcessInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* int32 pid = 2; */
        if (message.pid !== 0)
            writer.tag(2, WireType.Varint).int32(message.pid);
        /* double mem_mb = 3; */
        if (message.memMb !== 0)
            writer.tag(3, WireType.Bit64).double(message.memMb);
        /* double cpu_percent = 4; */
        if (message.cpuPercent !== 0)
            writer.tag(4, WireType.Bit64).double(message.cpuPercent);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.ProcessInfo
 */
export const ProcessInfo = new ProcessInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Event$Type extends MessageType<Event> {
    constructor() {
        super("hub.Event", [
            { no: 1, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "data", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Event>): Event {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = "";
        message.path = "";
        message.data = "";
        if (value !== undefined)
            reflectionMergePartial<Event>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Event): Event {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string type */ 1:
                    message.type = reader.string();
                    break;
                case /* string path */ 2:
                    message.path = reader.string();
                    break;
                case /* string data */ 3:
                    message.data = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Event, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string type = 1; */
        if (message.type !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.type);
        /* string path = 2; */
        if (message.path !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.path);
        /* string data = 3; */
        if (message.data !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.data);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.Event
 */
export const Event = new Event$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScanRequest$Type extends MessageType<ScanRequest> {
    constructor() {
        super("hub.ScanRequest", [
            { no: 1, name: "directory", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "root", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ScanRequest>): ScanRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.directory = "";
        message.root = "";
        if (value !== undefined)
            reflectionMergePartial<ScanRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScanRequest): ScanRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string directory */ 1:
                    message.directory = reader.string();
                    break;
                case /* string root */ 2:
                    message.root = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScanRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string directory = 1; */
        if (message.directory !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.directory);
        /* string root = 2; */
        if (message.root !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.root);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.ScanRequest
 */
export const ScanRequest = new ScanRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FileMetadata$Type extends MessageType<FileMetadata> {
    constructor() {
        super("hub.FileMetadata", [
            { no: 1, name: "path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "loc", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "sloc", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "comments", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "intent", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<FileMetadata>): FileMetadata {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.path = "";
        message.loc = 0;
        message.sloc = 0;
        message.comments = 0;
        message.intent = "";
        if (value !== undefined)
            reflectionMergePartial<FileMetadata>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FileMetadata): FileMetadata {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string path */ 1:
                    message.path = reader.string();
                    break;
                case /* int32 loc */ 2:
                    message.loc = reader.int32();
                    break;
                case /* int32 sloc */ 3:
                    message.sloc = reader.int32();
                    break;
                case /* int32 comments */ 4:
                    message.comments = reader.int32();
                    break;
                case /* string intent */ 5:
                    message.intent = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FileMetadata, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string path = 1; */
        if (message.path !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.path);
        /* int32 loc = 2; */
        if (message.loc !== 0)
            writer.tag(2, WireType.Varint).int32(message.loc);
        /* int32 sloc = 3; */
        if (message.sloc !== 0)
            writer.tag(3, WireType.Varint).int32(message.sloc);
        /* int32 comments = 4; */
        if (message.comments !== 0)
            writer.tag(4, WireType.Varint).int32(message.comments);
        /* string intent = 5; */
        if (message.intent !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.intent);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.FileMetadata
 */
export const FileMetadata = new FileMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScanResponse$Type extends MessageType<ScanResponse> {
    constructor() {
        super("hub.ScanResponse", [
            { no: 1, name: "files", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => FileMetadata }
        ]);
    }
    create(value?: PartialMessage<ScanResponse>): ScanResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.files = [];
        if (value !== undefined)
            reflectionMergePartial<ScanResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScanResponse): ScanResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated hub.FileMetadata files */ 1:
                    message.files.push(FileMetadata.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScanResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated hub.FileMetadata files = 1; */
        for (let i = 0; i < message.files.length; i++)
            FileMetadata.internalBinaryWrite(message.files[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.ScanResponse
 */
export const ScanResponse = new ScanResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AnalyzeRequest$Type extends MessageType<AnalyzeRequest> {
    constructor() {
        super("hub.AnalyzeRequest", [
            { no: 1, name: "file", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AnalyzeRequest>): AnalyzeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.file = "";
        message.content = "";
        if (value !== undefined)
            reflectionMergePartial<AnalyzeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AnalyzeRequest): AnalyzeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string file */ 1:
                    message.file = reader.string();
                    break;
                case /* string content */ 2:
                    message.content = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AnalyzeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string file = 1; */
        if (message.file !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.file);
        /* string content = 2; */
        if (message.content !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.content);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.AnalyzeRequest
 */
export const AnalyzeRequest = new AnalyzeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AnalyzeResponse$Type extends MessageType<AnalyzeResponse> {
    constructor() {
        super("hub.AnalyzeResponse", [
            { no: 1, name: "json_data", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AnalyzeResponse>): AnalyzeResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.jsonData = "";
        if (value !== undefined)
            reflectionMergePartial<AnalyzeResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AnalyzeResponse): AnalyzeResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string json_data */ 1:
                    message.jsonData = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AnalyzeResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string json_data = 1; */
        if (message.jsonData !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.jsonData);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.AnalyzeResponse
 */
export const AnalyzeResponse = new AnalyzeResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TaskRequest$Type extends MessageType<TaskRequest> {
    constructor() {
        super("hub.TaskRequest", [
            { no: 1, name: "task_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "target_file", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TaskRequest>): TaskRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.taskType = "";
        message.targetFile = "";
        if (value !== undefined)
            reflectionMergePartial<TaskRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TaskRequest): TaskRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string task_type */ 1:
                    message.taskType = reader.string();
                    break;
                case /* string target_file */ 2:
                    message.targetFile = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TaskRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string task_type = 1; */
        if (message.taskType !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.taskType);
        /* string target_file = 2; */
        if (message.targetFile !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.targetFile);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.TaskRequest
 */
export const TaskRequest = new TaskRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TaskResponse$Type extends MessageType<TaskResponse> {
    constructor() {
        super("hub.TaskResponse", [
            { no: 1, name: "task_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<TaskResponse>): TaskResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.taskId = 0;
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<TaskResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TaskResponse): TaskResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 task_id */ 1:
                    message.taskId = reader.int32();
                    break;
                case /* bool success */ 2:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TaskResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 task_id = 1; */
        if (message.taskId !== 0)
            writer.tag(1, WireType.Varint).int32(message.taskId);
        /* bool success = 2; */
        if (message.success !== false)
            writer.tag(2, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.TaskResponse
 */
export const TaskResponse = new TaskResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PendingRequest$Type extends MessageType<PendingRequest> {
    constructor() {
        super("hub.PendingRequest", [
            { no: 1, name: "limit", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<PendingRequest>): PendingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.limit = 0;
        if (value !== undefined)
            reflectionMergePartial<PendingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PendingRequest): PendingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 limit */ 1:
                    message.limit = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PendingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 limit = 1; */
        if (message.limit !== 0)
            writer.tag(1, WireType.Varint).int32(message.limit);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.PendingRequest
 */
export const PendingRequest = new PendingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Task$Type extends MessageType<Task> {
    constructor() {
        super("hub.Task", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "task_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "target_file", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "result", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Task>): Task {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.taskType = "";
        message.targetFile = "";
        message.status = "";
        message.result = "";
        message.createdAt = "";
        if (value !== undefined)
            reflectionMergePartial<Task>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Task): Task {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string task_type */ 2:
                    message.taskType = reader.string();
                    break;
                case /* string target_file */ 3:
                    message.targetFile = reader.string();
                    break;
                case /* string status */ 4:
                    message.status = reader.string();
                    break;
                case /* string result */ 5:
                    message.result = reader.string();
                    break;
                case /* string created_at */ 6:
                    message.createdAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Task, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string task_type = 2; */
        if (message.taskType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.taskType);
        /* string target_file = 3; */
        if (message.targetFile !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.targetFile);
        /* string status = 4; */
        if (message.status !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.status);
        /* string result = 5; */
        if (message.result !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.result);
        /* string created_at = 6; */
        if (message.createdAt !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.createdAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.Task
 */
export const Task = new Task$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PendingResponse$Type extends MessageType<PendingResponse> {
    constructor() {
        super("hub.PendingResponse", [
            { no: 1, name: "tasks", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Task }
        ]);
    }
    create(value?: PartialMessage<PendingResponse>): PendingResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tasks = [];
        if (value !== undefined)
            reflectionMergePartial<PendingResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PendingResponse): PendingResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated hub.Task tasks */ 1:
                    message.tasks.push(Task.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PendingResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated hub.Task tasks = 1; */
        for (let i = 0; i < message.tasks.length; i++)
            Task.internalBinaryWrite(message.tasks[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.PendingResponse
 */
export const PendingResponse = new PendingResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateTaskRequest$Type extends MessageType<UpdateTaskRequest> {
    constructor() {
        super("hub.UpdateTaskRequest", [
            { no: 1, name: "task_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "result", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateTaskRequest>): UpdateTaskRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.taskId = 0;
        message.status = "";
        message.result = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateTaskRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateTaskRequest): UpdateTaskRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 task_id */ 1:
                    message.taskId = reader.int32();
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                case /* string result */ 3:
                    message.result = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateTaskRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 task_id = 1; */
        if (message.taskId !== 0)
            writer.tag(1, WireType.Varint).int32(message.taskId);
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        /* string result = 3; */
        if (message.result !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.result);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.UpdateTaskRequest
 */
export const UpdateTaskRequest = new UpdateTaskRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeduplicateRequest$Type extends MessageType<DeduplicateRequest> {
    constructor() {
        super("hub.DeduplicateRequest", [
            { no: 1, name: "findings_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeduplicateRequest>): DeduplicateRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.findingsJson = "";
        if (value !== undefined)
            reflectionMergePartial<DeduplicateRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeduplicateRequest): DeduplicateRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string findings_json */ 1:
                    message.findingsJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeduplicateRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string findings_json = 1; */
        if (message.findingsJson !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.findingsJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.DeduplicateRequest
 */
export const DeduplicateRequest = new DeduplicateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConnectivityRequest$Type extends MessageType<ConnectivityRequest> {
    constructor() {
        super("hub.ConnectivityRequest", [
            { no: 1, name: "dependency_map_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ConnectivityRequest>): ConnectivityRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.dependencyMapJson = "";
        if (value !== undefined)
            reflectionMergePartial<ConnectivityRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConnectivityRequest): ConnectivityRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string dependency_map_json */ 1:
                    message.dependencyMapJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConnectivityRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string dependency_map_json = 1; */
        if (message.dependencyMapJson !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.dependencyMapJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.ConnectivityRequest
 */
export const ConnectivityRequest = new ConnectivityRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AuditRequest$Type extends MessageType<AuditRequest> {
    constructor() {
        super("hub.AuditRequest", [
            { no: 1, name: "audit_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AuditRequest>): AuditRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.auditJson = "";
        if (value !== undefined)
            reflectionMergePartial<AuditRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AuditRequest): AuditRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string audit_json */ 1:
                    message.auditJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AuditRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string audit_json = 1; */
        if (message.auditJson !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.auditJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.AuditRequest
 */
export const AuditRequest = new AuditRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BatchRequest$Type extends MessageType<BatchRequest> {
    constructor() {
        super("hub.BatchRequest", [
            { no: 1, name: "batch_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<BatchRequest>): BatchRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.batchJson = "";
        if (value !== undefined)
            reflectionMergePartial<BatchRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BatchRequest): BatchRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string batch_json */ 1:
                    message.batchJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BatchRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string batch_json = 1; */
        if (message.batchJson !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.batchJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.BatchRequest
 */
export const BatchRequest = new BatchRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReasonRequest$Type extends MessageType<ReasonRequest> {
    constructor() {
        super("hub.ReasonRequest", [
            { no: 1, name: "prompt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "use_rag", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ReasonRequest>): ReasonRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.prompt = "";
        message.useRag = false;
        if (value !== undefined)
            reflectionMergePartial<ReasonRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReasonRequest): ReasonRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string prompt */ 1:
                    message.prompt = reader.string();
                    break;
                case /* bool use_rag */ 2:
                    message.useRag = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReasonRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string prompt = 1; */
        if (message.prompt !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.prompt);
        /* bool use_rag = 2; */
        if (message.useRag !== false)
            writer.tag(2, WireType.Varint).bool(message.useRag);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.ReasonRequest
 */
export const ReasonRequest = new ReasonRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PatternRequest$Type extends MessageType<PatternRequest> {
    constructor() {
        super("hub.PatternRequest", [
            { no: 1, name: "pattern_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PatternRequest>): PatternRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.patternJson = "";
        if (value !== undefined)
            reflectionMergePartial<PatternRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PatternRequest): PatternRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string pattern_json */ 1:
                    message.patternJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PatternRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string pattern_json = 1; */
        if (message.patternJson !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.patternJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.PatternRequest
 */
export const PatternRequest = new PatternRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PenaltyRequest$Type extends MessageType<PenaltyRequest> {
    constructor() {
        super("hub.PenaltyRequest", [
            { no: 1, name: "penalty_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PenaltyRequest>): PenaltyRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.penaltyJson = "";
        if (value !== undefined)
            reflectionMergePartial<PenaltyRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PenaltyRequest): PenaltyRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string penalty_json */ 1:
                    message.penaltyJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PenaltyRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string penalty_json = 1; */
        if (message.penaltyJson !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.penaltyJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.PenaltyRequest
 */
export const PenaltyRequest = new PenaltyRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScoreRequest$Type extends MessageType<ScoreRequest> {
    constructor() {
        super("hub.ScoreRequest", [
            { no: 1, name: "score_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ScoreRequest>): ScoreRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.scoreJson = "";
        if (value !== undefined)
            reflectionMergePartial<ScoreRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScoreRequest): ScoreRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string score_json */ 1:
                    message.scoreJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScoreRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string score_json = 1; */
        if (message.scoreJson !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.scoreJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.ScoreRequest
 */
export const ScoreRequest = new ScoreRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CoverageRequest$Type extends MessageType<CoverageRequest> {
    constructor() {
        super("hub.CoverageRequest", [
            { no: 1, name: "coverage_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CoverageRequest>): CoverageRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.coverageJson = "";
        if (value !== undefined)
            reflectionMergePartial<CoverageRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CoverageRequest): CoverageRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string coverage_json */ 1:
                    message.coverageJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CoverageRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string coverage_json = 1; */
        if (message.coverageJson !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.coverageJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.CoverageRequest
 */
export const CoverageRequest = new CoverageRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GraphRequest$Type extends MessageType<GraphRequest> {
    constructor() {
        super("hub.GraphRequest", [
            { no: 1, name: "graph_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GraphRequest>): GraphRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.graphJson = "";
        if (value !== undefined)
            reflectionMergePartial<GraphRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GraphRequest): GraphRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string graph_json */ 1:
                    message.graphJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GraphRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string graph_json = 1; */
        if (message.graphJson !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.graphJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.GraphRequest
 */
export const GraphRequest = new GraphRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QueryRequest$Type extends MessageType<QueryRequest> {
    constructor() {
        super("hub.QueryRequest", [
            { no: 1, name: "query_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<QueryRequest>): QueryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.queryJson = "";
        if (value !== undefined)
            reflectionMergePartial<QueryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QueryRequest): QueryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string query_json */ 1:
                    message.queryJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: QueryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string query_json = 1; */
        if (message.queryJson !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.queryJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.QueryRequest
 */
export const QueryRequest = new QueryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HealingPlan$Type extends MessageType<HealingPlan> {
    constructor() {
        super("hub.HealingPlan", [
            { no: 1, name: "issue_description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "file_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "file_content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "context", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<HealingPlan>): HealingPlan {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.issueDescription = "";
        message.filePath = "";
        message.fileContent = "";
        message.context = "";
        if (value !== undefined)
            reflectionMergePartial<HealingPlan>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HealingPlan): HealingPlan {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string issue_description */ 1:
                    message.issueDescription = reader.string();
                    break;
                case /* string file_path */ 2:
                    message.filePath = reader.string();
                    break;
                case /* string file_content */ 3:
                    message.fileContent = reader.string();
                    break;
                case /* string context */ 4:
                    message.context = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HealingPlan, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string issue_description = 1; */
        if (message.issueDescription !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.issueDescription);
        /* string file_path = 2; */
        if (message.filePath !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.filePath);
        /* string file_content = 3; */
        if (message.fileContent !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.fileContent);
        /* string context = 4; */
        if (message.context !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.context);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message hub.HealingPlan
 */
export const HealingPlan = new HealingPlan$Type();
/**
 * @generated ServiceType for protobuf service hub.HubService
 */
export const HubService = new ServiceType("hub.HubService", [
    { name: "GetStatus", options: {}, I: Empty, O: StatusResponse },
    { name: "WatchHealth", serverStreaming: true, options: {}, I: Empty, O: HealthUpdate },
    { name: "WatchEvents", serverStreaming: true, options: {}, I: Empty, O: Event },
    { name: "ScanProject", options: {}, I: ScanRequest, O: ScanResponse },
    { name: "AnalyzeFile", options: {}, I: AnalyzeRequest, O: AnalyzeResponse },
    { name: "AnalyzeStream", serverStreaming: true, clientStreaming: true, options: {}, I: AnalyzeRequest, O: AnalyzeResponse },
    { name: "GetDependencies", options: {}, I: AnalyzeRequest, O: AnalyzeResponse },
    { name: "Deduplicate", options: {}, I: DeduplicateRequest, O: AnalyzeResponse },
    { name: "Fingerprint", options: {}, I: AnalyzeRequest, O: AnalyzeResponse },
    { name: "DiscoverIdentity", options: {}, I: AnalyzeRequest, O: AnalyzeResponse },
    { name: "IndexProject", options: {}, I: AnalyzeRequest, O: AnalyzeResponse },
    { name: "ScanTopology", options: {}, I: AnalyzeRequest, O: AnalyzeResponse },
    { name: "GetContext", options: {}, I: AnalyzeRequest, O: AnalyzeResponse },
    { name: "GetConnectivity", options: {}, I: ConnectivityRequest, O: AnalyzeResponse },
    { name: "Audit", options: {}, I: AuditRequest, O: AnalyzeResponse },
    { name: "Batch", options: {}, I: BatchRequest, O: AnalyzeResponse },
    { name: "Reason", options: {}, I: ReasonRequest, O: AnalyzeResponse },
    { name: "Patterns", options: {}, I: PatternRequest, O: AnalyzeResponse },
    { name: "Penalty", options: {}, I: PenaltyRequest, O: AnalyzeResponse },
    { name: "CalculateScore", options: {}, I: ScoreRequest, O: AnalyzeResponse },
    { name: "AuditCoverage", options: {}, I: CoverageRequest, O: AnalyzeResponse },
    { name: "GetKnowledgeGraph", options: {}, I: GraphRequest, O: AnalyzeResponse },
    { name: "QueryKnowledgeGraph", options: {}, I: QueryRequest, O: AnalyzeResponse },
    { name: "ExecuteHealing", options: {}, I: HealingPlan, O: AnalyzeResponse },
    { name: "EnqueueTask", options: {}, I: TaskRequest, O: TaskResponse },
    { name: "GetPendingTasks", options: {}, I: PendingRequest, O: PendingResponse },
    { name: "UpdateTask", options: {}, I: UpdateTaskRequest, O: Empty }
]);
/**
 * @generated ServiceType for protobuf service hub.RuleProvider
 */
export const RuleProvider = new ServiceType("hub.RuleProvider", [
    { name: "GetRules", options: {}, I: RuleRequest, O: RuleResponse },
    { name: "AnalyzeCode", options: {}, I: AnalyzeCodeRequest, O: AnalyzeResponse }
]);
