use crate::core::base::{BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext};
use crate::core::types::MetricData;

/**
 * 📢 Dr. Echo — PhD in System Feedback & Content Integrity
 * Generated by Sovereign Forge.
 */
pub struct EchoPersona {
    base: BaseActivePersona,
}

impl EchoPersona {
    pub fn new(project_root: Option<String>) -> Self {
        Self {
            base: BaseActivePersona::new(
                "Echo".to_string(),
                "📢".to_string(),
                "PhD Communication Specialist".to_string(),
                "System Feedback & Content Integrity".to_string(),
                "Rust".to_string(),
                "".to_string(),
                project_root,
            ),
        }
    }

    pub fn get_audit_rules(&self) -> (Vec<String>, Vec<AuditRule>) {
        (
            [".rs"].iter().map(|s| s.to_string()).collect(),
            vec![
                /* [
          {
                    "regex": "console\\.log\\(",
                    "issue": "Feedback: console.log detectado. Use o Logger PhD para rastreabilidade soberana.",
                    "severity": "medium"
          }
] */
            ]
        )
    }

    pub fn perform_audit(&self) {
        println!("🦀 [{}] Starting fleet-wide audit via Hub PhD...", self.base.name);
        // delegation logic using tonic gRPC client
        // The original comment "Logic will be delegated via gRPC HubClient."
        // and "Vec::new()" were likely placeholders for this delegation.
    }

    pub fn reason_about_objective(&self, objective: &str, file: &str, context: &str) {
        println!("🦀 [{}] Delegating reasoning for '{}' to Hub...", self.base.name, objective);
    }

    pub fn delegate_healing_to_hub(&self, file: &str, issue: &str) {
        println!("🦀 [{}] Delegating healing for '{}' to Hub...", self.base.name, issue);
    }
}
