use crate::core::base::{BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext};
use crate::core::types::MetricData;

/**
 * 🧬 Dr. Generic — PhD in Generics & Type Algebra (TypeScript)
 * Generated by Sovereign Forge.
 */
pub struct GenericPersona {
    base: BaseActivePersona,
}

impl GenericPersona {
    pub fn new(project_root: Option<String>) -> Self {
        Self {
            base: BaseActivePersona::new(
                "Generic".to_string(),
                "🧬".to_string(),
                "PhD TypeScript Type Algebraist".to_string(),
                "Generics & Type Algebra (TypeScript)".to_string(),
                "Rust".to_string(),
                "".to_string(),
                project_root,
            ),
        }
    }

    pub fn get_audit_rules(&self) -> (Vec<String>, Vec<AuditRule>) {
        (
            [".rs"].iter().map(|s| s.to_string()).collect(),
            vec![
                /* [
          {
                    "regex": "<[^>]*<[^>]*<[^>]*>>",
                    "issue": "Complexidade: Generics com 3+ níveis de aninhamento — simplificar com type aliases.",
                    "severity": "medium"
          },
          {
                    "regex": "extends\\s+infer\\s+\\w+.*extends\\s+infer",
                    "issue": "Magia Negra: Múltiplos \"infer\" condicionais — difícil de manter.",
                    "severity": "high"
          },
          {
                    "regex": "type\\s+\\w+<[^>]*>\\s*=\\s*\\w+<[^>]*>\\s*extends\\s",
                    "issue": "Tipo Condicional: Conditional type — verifique se não há alternativa simples.",
                    "severity": "low"
          },
          {
                    "regex": "as\\s+unknown\\s+as\\s+",
                    "issue": "Double Cast: \"as unknown as X\" — forte indicador de design errado.",
                    "severity": "high"
          }
] */
            ]
        )
    }

    pub fn perform_audit(&self) {
        println!("🦀 [{}] Starting fleet-wide audit via Hub PhD...", self.base.name);
        // delegation logic using tonic gRPC client
        // The original comment "Logic will be delegated via gRPC HubClient."
        // and "Vec::new()" were likely placeholders for this delegation.
    }

    pub fn reason_about_objective(&self, objective: &str, file: &str, context: &str) {
        println!("🦀 [{}] Delegating reasoning for '{}' to Hub...", self.base.name, objective);
    }

    pub fn delegate_healing_to_hub(&self, file: &str, issue: &str) {
        println!("🦀 [{}] Delegating healing for '{}' to Hub...", self.base.name, issue);
    }
}
