import { BaseActivePersona } from "../../base.ts";
import type { AuditRule, StrategicFinding, AuditFinding, ProjectContext } from "../../base.ts";

/**
 * 🎀 Dr. Decorator — PhD in TypeScript Metaprogramming & Reflection (TypeScript)
 * Generated by Sovereign Forge.
 */
export class DecoratorPersona extends BaseActivePersona {
    constructor(projectRoot: string | undefined = undefined) {
        super(projectRoot);
        this.id = "decorator";
        this.name = "Decorator";
        this.emoji = "🎀";
        this.role = "PhD TypeScript Metaprogramming Engineer";
        this.phd_identity = "TypeScript Metaprogramming & Reflection (TypeScript)";
        this.stack = "TypeScript";
        this.healingPrompt = "";
    }

    override async execute(context: ProjectContext): Promise<(AuditFinding | StrategicFinding)[]> {
        this.setContext(context);
        const findings = await this.performAudit();
        return findings;
    }

    override getAuditRules(): { extensions: string[]; rules: AuditRule[] } {
        return {
            extensions: [".ts",".tsx"],
            rules: [
          {
                    "regex": "@\\w+\\s*\\(\\)\\s*\\n\\s*@\\w+\\s*\\(\\)\\s*\\n\\s*@\\w+",
                    "issue": "Sobrecarga: 3+ decoradores empilhados — complexidade de metaprogramação PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "experimentalDecorators",
                    "issue": "Experimental: Usando decoradores experimentais — migre para TC39 Stage 3 PhD.",
                    "severity": "low"
          },
          {
                    "regex": "reflect-metadata",
                    "issue": "Dependência Pesada: reflect-metadata adiciona overhead de runtime PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "@Injectable|@Component|@Module",
                    "issue": "Framework DI: Decoradores de injeção de dependência — verifique acoplamento PhD.",
                    "severity": "low"
          }
]
        };
    }

    public override async performAudit(): Promise<AuditFinding[]> {
        this.startMetrics();
        
        const allFindings: AuditFinding[] = [];
        const files = Object.keys(this.contextData);
        
        for (const file of files) {
            const results = await this.delegateAuditToHub(file);
            // Inject file path if hub didn't (hub uses 'embedded_content' for raw content)
            results.forEach(f => {
                if (f.file === "embedded_content") f.file = file;
                allFindings.push(f);
            });
        }
        
        this.endMetrics(allFindings.length);
        return allFindings;
    }

    public override async reasonAboutObjective(objective: string, file: string, context: string): Promise<StrategicFinding | null> {
        return await super.reasonAboutObjective(objective, file, context);
    }

    override selfDiagnostic(): any {
        return { status: "Soberano", score: 100, details: "Módulo Decorator operando com paridade total via Forge." };
    }

    override getSystemPrompt(): string {
        return `Você é o Dr. Decorator, PhD em TypeScript Metaprogramming & Reflection (TypeScript). Sua missão é garantir a excelência via governança PhD.`;
    }
}
