import { BaseActivePersona } from "../../base.ts";
import type { AuditRule, StrategicFinding, AuditFinding, ProjectContext } from "../../base.ts";

/**
 * 💾 Dr. Cache — PhD in Data Layer & I/O Optimization (TypeScript)
 * Generated by Sovereign Forge.
 */
export class CachePersona extends BaseActivePersona {
    constructor(projectRoot: string | undefined = undefined) {
        super(projectRoot);
        this.id = "cache";
        this.name = "Cache";
        this.emoji = "💾";
        this.role = "PhD Data Layer Engineer";
        this.phd_identity = "Data Layer & I/O Optimization (TypeScript)";
        this.stack = "TypeScript";
        this.healingPrompt = "";
    }

    override async execute(context: ProjectContext): Promise<(AuditFinding | StrategicFinding)[]> {
        this.setContext(context);
        const findings = await this.performAudit();
        return findings;
    }

    override getAuditRules(): { extensions: string[]; rules: AuditRule[] } {
        return {
            extensions: [".ts",".tsx",".js"],
            rules: [
          {
                    "regex": "readFileSync\\(",
                    "issue": "Bloqueio de I/O: readFileSync trava o event loop PhD.",
                    "severity": "high"
          },
          {
                    "regex": "writeFileSync\\(",
                    "issue": "Bloqueio de I/O: writeFileSync trava o event loop PhD.",
                    "severity": "high"
          },
          {
                    "regex": "fs\\.(?:read|write|stat|access)(?!.*Sync)(?!.*await|promise)",
                    "issue": "Callback I/O: Operação de arquivo via callback — use fs/promises PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "new Map\\(\\).*(?:set|get).*(?:set|get).*(?:set|get)",
                    "issue": "Cache Ingênuo: Map como cache sem TTL ou eviction — risco de memory leak PhD.",
                    "severity": "medium"
          }
]
        };
    }

    public override async performAudit(): Promise<AuditFinding[]> {
        this.startMetrics();
        
        const allFindings: AuditFinding[] = [];
        const files = Object.keys(this.contextData);
        
        for (const file of files) {
            const results = await this.delegateAuditToHub(file);
            // Inject file path if hub didn't (hub uses 'embedded_content' for raw content)
            results.forEach(f => {
                if (f.file === "embedded_content") f.file = file;
                allFindings.push(f);
            });
        }
        
        this.endMetrics(allFindings.length);
        return allFindings;
    }

    public override async reasonAboutObjective(objective: string, file: string, context: string): Promise<StrategicFinding | null> {
        return await super.reasonAboutObjective(objective, file, context);
    }

    override selfDiagnostic(): any {
        return { status: "Soberano", score: 100, details: "Módulo Cache operando com paridade total via Forge." };
    }

    override getSystemPrompt(): string {
        return `Você é o Dr. Cache, PhD em Data Layer & I/O Optimization (TypeScript). Sua missão é garantir a excelência via governança PhD.`;
    }
}
