import { BaseActivePersona } from "../../base.ts";
import type { AuditRule, StrategicFinding, AuditFinding, HealingResult, ProjectContext } from "../../base.ts";

/**
 * ⚡ Dr. Bolt — PhD in Low-Latency & Concurrency Optimization
 * Generated by Sovereign Forge.
 */
export class BoltPersona extends BaseActivePersona {
    constructor(projectRoot: string | undefined = undefined) {
        super(projectRoot);
        this.id = "bolt";
        this.name = "Bolt";
        this.emoji = "⚡";
        this.role = "PhD Performance Engineer";
        this.phd_identity = "Low-Latency & Concurrency Optimization";
        this.stack = "Bun";
        this.healingPrompt = "Refactor the following code to improve performance and concurrency as per PhD standards. Use high-efficiency patterns (e.g., replace forEach with for-of, minimize lock contention). Return ONLY the corrected code or a specific diff.";
    }

    override async execute(context: ProjectContext): Promise<(AuditFinding | StrategicFinding)[]> {
        this.setContext(context);
        if (this.healingPrompt) {
            const { findings } = await this.auditAndHeal();
            return findings;
        }
        const findings = await this.performAudit();
        return findings;
    }

    override getAuditRules(): { extensions: string[]; rules: AuditRule[] } {
        return {
            extensions: [".ts",".js"],
            rules: [
          {
                    "regex": "\\.forEach\\(",
                    "issue": "Performance: forEach detectado. Use for-of ou for loops em caminhos críticos para otimização JIT PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "new Array\\(\\)",
                    "issue": "Performance: Alocação de array vazia. Use literais ou pré-alocação se o tamanho for conhecido PhD.",
                    "severity": "low"
          }
]
        };
    }

    public override async performAudit(): Promise<AuditFinding[]> {
        this.startMetrics();
        
        const allFindings: AuditFinding[] = [];
        const files = Object.keys(this.contextData);
        
        for (const file of files) {
            const results = await this.delegateAuditToHub(file);
            // Inject file path if hub didn't (hub uses 'embedded_content' for raw content)
            results.forEach(f => {
                if (f.file === "embedded_content") f.file = file;
                allFindings.push(f);
            });
        }
        
        this.endMetrics(allFindings.length);
        return allFindings;
    }

    public override async reasonAboutObjective(objective: string, file: string, context: string): Promise<StrategicFinding | null> {
        return await super.reasonAboutObjective(objective, file, context);
    }

    override selfDiagnostic(): any {
        return { status: "Soberano", score: 100, details: "Módulo Bolt operando com paridade total via Forge." };
    }

    override getSystemPrompt(): string {
        return `Você é o Dr. Bolt, PhD em Low-Latency & Concurrency Optimization. Sua missão é garantir a excelência via governança PhD.`;
    }
}
