import { BaseActivePersona } from "../../base.ts";
import type { AuditRule, StrategicFinding, AuditFinding, HealingResult, ProjectContext } from "../../base.ts";

/**
 * 🔬 Dr. Probe — PhD in TypeScript Error Resilience & Exception Handling
 * Generated by Sovereign Forge.
 */
export class ProbePersona extends BaseActivePersona {
    constructor(projectRoot: string | undefined = undefined) {
        super(projectRoot);
        this.id = "probe";
        this.name = "Probe";
        this.emoji = "🔬";
        this.role = "PhD Resilience Engineer";
        this.phd_identity = "TypeScript Error Resilience & Exception Handling";
        this.stack = "Bun";
        this.healingPrompt = "Fix the following runtime diagnostics or health check issue. Ensure proper health endpoints, timeout handling, and liveness probes. Return ONLY the corrected code or a specific diff.";
    }

    override async execute(context: ProjectContext): Promise<(AuditFinding | StrategicFinding)[]> {
        this.setContext(context);
        if (this.healingPrompt) {
            const { findings } = await this.auditAndHeal();
            return findings;
        }
        const findings = await this.performAudit();
        return findings;
    }

    override getAuditRules(): { extensions: string[]; rules: AuditRule[] } {
        return {
            extensions: [".ts",".js"],
            rules: [
          {
                    "regex": "catch\\s*\\([^)]*\\)\\s*\\{\\s*\\}",
                    "issue": "Silenciado: catch vazio engole exceção sem tratamento.",
                    "severity": "critical"
          },
          {
                    "regex": "catch\\s*\\{\\s*\\}",
                    "issue": "Silenciado: catch vazio sem parâmetro.",
                    "severity": "critical"
          },
          {
                    "regex": "\\.catch\\(\\(\\)\\s*=>\\s*\\{\\s*\\}\\)",
                    "issue": "Silenciado: Promise .catch vazio engole rejeição.",
                    "severity": "critical"
          },
          {
                    "regex": "\\.catch\\(\\(\\)\\s*=>\\s*null\\)",
                    "issue": "Suprimido: Promise .catch retorna null — erro perdido.",
                    "severity": "high"
          },
          {
                    "regex": "throw\\s+new\\s+Error\\(\\)",
                    "issue": "Vago: Error lançado sem mensagem descritiva.",
                    "severity": "medium"
          }
]
        };
    }

    public override async performAudit(): Promise<AuditFinding[]> {
        this.startMetrics();
        
        const allFindings: AuditFinding[] = [];
        const files = Object.keys(this.contextData);
        
        for (const file of files) {
            const results = await this.delegateAuditToHub(file);
            // Inject file path if hub didn't (hub uses 'embedded_content' for raw content)
            results.forEach(f => {
                if (f.file === "embedded_content") f.file = file;
                allFindings.push(f);
            });
        }
        
        this.endMetrics(allFindings.length);
        return allFindings;
    }

    public override async reasonAboutObjective(objective: string, file: string, context: string): Promise<StrategicFinding | null> {
        return await super.reasonAboutObjective(objective, file, context);
    }

    override selfDiagnostic(): any {
        return { status: "Soberano", score: 100, details: "Módulo Probe operando com paridade total via Forge." };
    }

    override getSystemPrompt(): string {
        return `Você é o Dr. Probe, PhD em TypeScript Error Resilience & Exception Handling. Sua missão é garantir a excelência via governança PhD.`;
    }
}
