import { BaseActivePersona } from "../../base.ts";
import type { AuditRule, StrategicFinding, AuditFinding, HealingResult, ProjectContext } from "../../base.ts";

/**
 * 🎯 Dr. Scope — PhD in TypeScript Project Management & Technical Debt
 * Generated by Sovereign Forge.
 */
export class ScopePersona extends BaseActivePersona {
    constructor(projectRoot: string | undefined = undefined) {
        super(projectRoot);
        this.id = "scope";
        this.name = "Scope";
        this.emoji = "🎯";
        this.role = "PhD Project Strategist";
        this.phd_identity = "TypeScript Project Management & Technical Debt";
        this.stack = "Bun";
        this.healingPrompt = "Fix the following scope analysis or variable lifecycle issue. Resolve variable shadowing, unused declarations, and scope leaks. Return ONLY the corrected code or a specific diff.";
    }

    override async execute(context: ProjectContext): Promise<(AuditFinding | StrategicFinding)[]> {
        this.setContext(context);
        if (this.healingPrompt) {
            const { findings } = await this.auditAndHeal();
            return findings;
        }
        const findings = await this.performAudit();
        return findings;
    }

    override getAuditRules(): { extensions: string[]; rules: AuditRule[] } {
        return {
            extensions: [".ts",".js"],
            rules: [
          {
                    "regex": "/\\/\\s*TODO[:\\s]/i",
                    "issue": "Dívida Técnica: TODO pendente — tarefa incompleta no código.",
                    "severity": "medium"
          },
          {
                    "regex": "/\\/\\s*FIXME[:\\s]/i",
                    "issue": "Dívida Crítica: FIXME — bug conhecido e aceito sem correção.",
                    "severity": "high"
          },
          {
                    "regex": "/\\/\\s*HACK[:\\s]/i",
                    "issue": "Gambiarra: HACK — solução temporária perigosa.",
                    "severity": "high"
          },
          {
                    "regex": "throw\\s+new\\s+Error\\([\"']not\\s+implemented/i",
                    "issue": "Incompleto: Funcionalidade declarada mas não implementada.",
                    "severity": "high"
          }
]
        };
    }

    public override async performAudit(): Promise<AuditFinding[]> {
        this.startMetrics();
        
        const allFindings: AuditFinding[] = [];
        const files = Object.keys(this.contextData);
        
        for (const file of files) {
            const results = await this.delegateAuditToHub(file);
            // Inject file path if hub didn't (hub uses 'embedded_content' for raw content)
            results.forEach(f => {
                if (f.file === "embedded_content") f.file = file;
                allFindings.push(f);
            });
        }
        
        this.endMetrics(allFindings.length);
        return allFindings;
    }

    public override async reasonAboutObjective(objective: string, file: string, context: string): Promise<StrategicFinding | null> {
        return await super.reasonAboutObjective(objective, file, context);
    }

    override selfDiagnostic(): any {
        return { status: "Soberano", score: 100, details: "Módulo Scope operando com paridade total via Forge." };
    }

    override getSystemPrompt(): string {
        return `Você é o Dr. Scope, PhD em TypeScript Project Management & Technical Debt. Sua missão é garantir a excelência via governança PhD.`;
    }
}
