import { BaseActivePersona } from "../../base.ts";
import type { AuditRule, StrategicFinding, AuditFinding, ProjectContext } from "../../base.ts";

/**
 * 🛡️ Dr. Strict — PhD in Type Safety & Memory Purity
 * Generated by Sovereign Forge.
 */
export class StrictPersona extends BaseActivePersona {
    constructor(projectRoot: string | undefined = undefined) {
        super(projectRoot);
        this.id = "strict";
        this.name = "Strict";
        this.emoji = "🛡️";
        this.role = "PhD Security & Type Integrity";
        this.phd_identity = "Type Safety & Memory Purity";
        this.stack = "Bun";
        this.healingPrompt = "Fix the following architectural or security violation. Ensure compliance with strict PhD guidelines (e.g., remove eval, enforce type safety, sanitize inputs). Return ONLY the corrected code or a specific diff.";
    }

    override async execute(context: ProjectContext): Promise<(AuditFinding | StrategicFinding)[]> {
        this.setContext(context);
        const findings = await this.performAudit();
        return findings;
    }

    override getAuditRules(): { extensions: string[]; rules: AuditRule[] } {
        return {
            extensions: [".ts",".js"],
            rules: [
          {
                    "regex": "as any",
                    "issue": "Integridade: Cast 'as any' detectado. Viola a segurança de tipos PhD.",
                    "severity": "critical"
          },
          {
                    "regex": "!",
                    "issue": "Integridade: Operador de asserção não-nula (!) detectado. Risco de runtime panic PhD.",
                    "severity": "high"
          }
]
        };
    }

    public override async performAudit(): Promise<AuditFinding[]> {
        this.startMetrics();
        
        const allFindings: AuditFinding[] = [];
        const files = Object.keys(this.contextData);
        
        for (const file of files) {
            const results = await this.delegateAuditToHub(file);
            // Inject file path if hub didn't (hub uses 'embedded_content' for raw content)
            results.forEach(f => {
                if (f.file === "embedded_content") f.file = file;
                allFindings.push(f);
            });
        }
        
        this.endMetrics(allFindings.length);
        return allFindings;
    }

    public override async reasonAboutObjective(objective: string, file: string, context: string): Promise<StrategicFinding | null> {
        return await super.reasonAboutObjective(objective, file, context);
    }

    override selfDiagnostic(): any {
        return { status: "Soberano", score: 100, details: "Módulo Strict operando com paridade total via Forge." };
    }

    override getSystemPrompt(): string {
        return `Você é o Dr. Strict, PhD em Type Safety & Memory Purity. Sua missão é garantir a excelência via governança PhD.`;
    }
}
