import { BaseActivePersona } from "../../base.ts";
import type { AuditRule, StrategicFinding, AuditFinding, HealingResult, ProjectContext } from "../../base.ts";

/**
 * 🌐 Dr. Web — PhD in Web Performance & DOM Integrity (TS/Bun)
 * Generated by Sovereign Forge.
 */
export class WebPersona extends BaseActivePersona {
    constructor(projectRoot: string | undefined = undefined) {
        super(projectRoot);
        this.id = "web";
        this.name = "Web";
        this.emoji = "🌐";
        this.role = "PhD Frontend Architect";
        this.phd_identity = "Web Performance & DOM Integrity (TS/Bun)";
        this.stack = "TypeScript";
        this.healingPrompt = "Fix the following web performance or DOM integrity issue. Eliminate layout shifts, optimize the critical rendering path, and fix reflow triggers. Return ONLY the corrected code or a specific diff.";
    }

    override async execute(context: ProjectContext): Promise<(AuditFinding | StrategicFinding)[]> {
        this.setContext(context);
        if (this.healingPrompt) {
            const { findings } = await this.auditAndHeal();
            return findings;
        }
        const findings = await this.performAudit();
        return findings;
    }

    override getAuditRules(): { extensions: string[]; rules: AuditRule[] } {
        return {
            extensions: [".ts",".tsx",".js",".jsx",".html"],
            rules: [
          {
                    "regex": "useEffect\\(\\(\\) => \\{[^\\]]*\\}, \\[\\]\\)",
                    "issue": "Hydration: Efeitos colaterais no mount sem verificação de window. Verifique se isso queima a hidratação no SSR.",
                    "severity": "medium"
          },
          {
                    "regex": "dangerouslySetInnerHTML",
                    "issue": "Security: Uso de dangerouslySetInnerHTML detectado. Risco de XSS se o conteúdo não for higienizado.",
                    "severity": "high"
          },
          {
                    "regex": "document\\.getElementById",
                    "issue": "DOM: Manipulação direta do DOM via 'document'. Prefira refs ou estados reativos para manter a integridade do VDOM.",
                    "severity": "low"
          }
]
        };
    }

    public override async performAudit(): Promise<AuditFinding[]> {
        this.startMetrics();
        
        const allFindings: AuditFinding[] = [];
        const files = Object.keys(this.contextData);
        
        for (const file of files) {
            const results = await this.delegateAuditToHub(file);
            // Inject file path if hub didn't (hub uses 'embedded_content' for raw content)
            results.forEach(f => {
                if (f.file === "embedded_content") f.file = file;
                allFindings.push(f);
            });
        }
        
        this.endMetrics(allFindings.length);
        return allFindings;
    }

    public override async reasonAboutObjective(objective: string, file: string, context: string): Promise<StrategicFinding | null> {
        return await super.reasonAboutObjective(objective, file, context);
    }

    override selfDiagnostic(): any {
        return { status: "Soberano", score: 100, details: "Módulo Web operando com paridade total via Forge." };
    }

    override getSystemPrompt(): string {
        return `Você é o Dr. Web, PhD em Web Performance & DOM Integrity (TS/Bun). Sua missão é garantir a excelência via governança PhD.`;
    }
}
