// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: hub.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HubService_GetStatus_FullMethodName       = "/hub.HubService/GetStatus"
	HubService_WatchHealth_FullMethodName     = "/hub.HubService/WatchHealth"
	HubService_WatchEvents_FullMethodName     = "/hub.HubService/WatchEvents"
	HubService_ScanProject_FullMethodName     = "/hub.HubService/ScanProject"
	HubService_AnalyzeFile_FullMethodName     = "/hub.HubService/AnalyzeFile"
	HubService_EnqueueTask_FullMethodName     = "/hub.HubService/EnqueueTask"
	HubService_GetPendingTasks_FullMethodName = "/hub.HubService/GetPendingTasks"
	HubService_UpdateTask_FullMethodName      = "/hub.HubService/UpdateTask"
)

// HubServiceClient is the client API for HubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HubServiceClient interface {
	// Health & Monitoring
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	WatchHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthUpdate], error)
	WatchEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Discovery & Analysis
	ScanProject(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	AnalyzeFile(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	// Task Scheduler
	EnqueueTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	GetPendingTasks(ctx context.Context, in *PendingRequest, opts ...grpc.CallOption) (*PendingResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*Empty, error)
}

type hubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHubServiceClient(cc grpc.ClientConnInterface) HubServiceClient {
	return &hubServiceClient{cc}
}

func (c *hubServiceClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, HubService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) WatchHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubService_ServiceDesc.Streams[0], HubService_WatchHealth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, HealthUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_WatchHealthClient = grpc.ServerStreamingClient[HealthUpdate]

func (c *hubServiceClient) WatchEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubService_ServiceDesc.Streams[1], HubService_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_WatchEventsClient = grpc.ServerStreamingClient[Event]

func (c *hubServiceClient) ScanProject(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, HubService_ScanProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) AnalyzeFile(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_AnalyzeFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) EnqueueTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, HubService_EnqueueTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetPendingTasks(ctx context.Context, in *PendingRequest, opts ...grpc.CallOption) (*PendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PendingResponse)
	err := c.cc.Invoke(ctx, HubService_GetPendingTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HubService_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HubServiceServer is the server API for HubService service.
// All implementations must embed UnimplementedHubServiceServer
// for forward compatibility.
type HubServiceServer interface {
	// Health & Monitoring
	GetStatus(context.Context, *Empty) (*StatusResponse, error)
	WatchHealth(*Empty, grpc.ServerStreamingServer[HealthUpdate]) error
	WatchEvents(*Empty, grpc.ServerStreamingServer[Event]) error
	// Discovery & Analysis
	ScanProject(context.Context, *ScanRequest) (*ScanResponse, error)
	AnalyzeFile(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	// Task Scheduler
	EnqueueTask(context.Context, *TaskRequest) (*TaskResponse, error)
	GetPendingTasks(context.Context, *PendingRequest) (*PendingResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*Empty, error)
	mustEmbedUnimplementedHubServiceServer()
}

// UnimplementedHubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHubServiceServer struct{}

func (UnimplementedHubServiceServer) GetStatus(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedHubServiceServer) WatchHealth(*Empty, grpc.ServerStreamingServer[HealthUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchHealth not implemented")
}
func (UnimplementedHubServiceServer) WatchEvents(*Empty, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedHubServiceServer) ScanProject(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanProject not implemented")
}
func (UnimplementedHubServiceServer) AnalyzeFile(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeFile not implemented")
}
func (UnimplementedHubServiceServer) EnqueueTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueTask not implemented")
}
func (UnimplementedHubServiceServer) GetPendingTasks(context.Context, *PendingRequest) (*PendingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingTasks not implemented")
}
func (UnimplementedHubServiceServer) UpdateTask(context.Context, *UpdateTaskRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedHubServiceServer) mustEmbedUnimplementedHubServiceServer() {}
func (UnimplementedHubServiceServer) testEmbeddedByValue()                    {}

// UnsafeHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubServiceServer will
// result in compilation errors.
type UnsafeHubServiceServer interface {
	mustEmbedUnimplementedHubServiceServer()
}

func RegisterHubServiceServer(s grpc.ServiceRegistrar, srv HubServiceServer) {
	// If the following call panics, it indicates UnimplementedHubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HubService_ServiceDesc, srv)
}

func _HubService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_WatchHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubServiceServer).WatchHealth(m, &grpc.GenericServerStream[Empty, HealthUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_WatchHealthServer = grpc.ServerStreamingServer[HealthUpdate]

func _HubService_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubServiceServer).WatchEvents(m, &grpc.GenericServerStream[Empty, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_WatchEventsServer = grpc.ServerStreamingServer[Event]

func _HubService_ScanProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).ScanProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_ScanProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).ScanProject(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_AnalyzeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).AnalyzeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_AnalyzeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).AnalyzeFile(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_EnqueueTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).EnqueueTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_EnqueueTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).EnqueueTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetPendingTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetPendingTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetPendingTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetPendingTasks(ctx, req.(*PendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HubService_ServiceDesc is the grpc.ServiceDesc for HubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hub.HubService",
	HandlerType: (*HubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _HubService_GetStatus_Handler,
		},
		{
			MethodName: "ScanProject",
			Handler:    _HubService_ScanProject_Handler,
		},
		{
			MethodName: "AnalyzeFile",
			Handler:    _HubService_AnalyzeFile_Handler,
		},
		{
			MethodName: "EnqueueTask",
			Handler:    _HubService_EnqueueTask_Handler,
		},
		{
			MethodName: "GetPendingTasks",
			Handler:    _HubService_GetPendingTasks_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _HubService_UpdateTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchHealth",
			Handler:       _HubService_WatchHealth_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchEvents",
			Handler:       _HubService_WatchEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hub.proto",
}
