// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: hub.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HubService_GetStatus_FullMethodName           = "/hub.HubService/GetStatus"
	HubService_WatchHealth_FullMethodName         = "/hub.HubService/WatchHealth"
	HubService_WatchEvents_FullMethodName         = "/hub.HubService/WatchEvents"
	HubService_ScanProject_FullMethodName         = "/hub.HubService/ScanProject"
	HubService_AnalyzeFile_FullMethodName         = "/hub.HubService/AnalyzeFile"
	HubService_AnalyzeStream_FullMethodName       = "/hub.HubService/AnalyzeStream"
	HubService_GetDependencies_FullMethodName     = "/hub.HubService/GetDependencies"
	HubService_Deduplicate_FullMethodName         = "/hub.HubService/Deduplicate"
	HubService_Fingerprint_FullMethodName         = "/hub.HubService/Fingerprint"
	HubService_DiscoverIdentity_FullMethodName    = "/hub.HubService/DiscoverIdentity"
	HubService_IndexProject_FullMethodName        = "/hub.HubService/IndexProject"
	HubService_ScanTopology_FullMethodName        = "/hub.HubService/ScanTopology"
	HubService_GetContext_FullMethodName          = "/hub.HubService/GetContext"
	HubService_GetConnectivity_FullMethodName     = "/hub.HubService/GetConnectivity"
	HubService_Audit_FullMethodName               = "/hub.HubService/Audit"
	HubService_Batch_FullMethodName               = "/hub.HubService/Batch"
	HubService_Reason_FullMethodName              = "/hub.HubService/Reason"
	HubService_Patterns_FullMethodName            = "/hub.HubService/Patterns"
	HubService_Penalty_FullMethodName             = "/hub.HubService/Penalty"
	HubService_CalculateScore_FullMethodName      = "/hub.HubService/CalculateScore"
	HubService_AuditCoverage_FullMethodName       = "/hub.HubService/AuditCoverage"
	HubService_GetKnowledgeGraph_FullMethodName   = "/hub.HubService/GetKnowledgeGraph"
	HubService_QueryKnowledgeGraph_FullMethodName = "/hub.HubService/QueryKnowledgeGraph"
	HubService_ExecuteHealing_FullMethodName      = "/hub.HubService/ExecuteHealing"
	HubService_RequestPeerReview_FullMethodName   = "/hub.HubService/RequestPeerReview"
	HubService_BroadcastSignal_FullMethodName     = "/hub.HubService/BroadcastSignal"
	HubService_Remember_FullMethodName            = "/hub.HubService/Remember"
	HubService_Retrieve_FullMethodName            = "/hub.HubService/Retrieve"
	HubService_Embed_FullMethodName               = "/hub.HubService/Embed"
	HubService_EnqueueTask_FullMethodName         = "/hub.HubService/EnqueueTask"
	HubService_GetPendingTasks_FullMethodName     = "/hub.HubService/GetPendingTasks"
	HubService_UpdateTask_FullMethodName          = "/hub.HubService/UpdateTask"
)

// HubServiceClient is the client API for HubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HubServiceClient interface {
	// Health & Monitoring
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	WatchHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthUpdate], error)
	WatchEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Discovery & Analysis
	ScanProject(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	AnalyzeFile(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	AnalyzeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AnalyzeRequest, AnalyzeResponse], error)
	GetDependencies(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	Deduplicate(ctx context.Context, in *DeduplicateRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	Fingerprint(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	DiscoverIdentity(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	IndexProject(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	ScanTopology(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	GetContext(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	GetConnectivity(ctx context.Context, in *ConnectivityRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	Audit(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	Reason(ctx context.Context, in *ReasonRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	Patterns(ctx context.Context, in *PatternRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	Penalty(ctx context.Context, in *PenaltyRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	CalculateScore(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	AuditCoverage(ctx context.Context, in *CoverageRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	GetKnowledgeGraph(ctx context.Context, in *GraphRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	QueryKnowledgeGraph(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	// Auto-Healing
	ExecuteHealing(ctx context.Context, in *HealingPlan, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	// Swarm Intelligence (Agent Collaboration)
	RequestPeerReview(ctx context.Context, in *PeerReviewRequest, opts ...grpc.CallOption) (*PeerReviewResponse, error)
	BroadcastSignal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*Empty, error)
	// Semantic Memory
	Remember(ctx context.Context, in *MemoryEntry, opts ...grpc.CallOption) (*Empty, error)
	Retrieve(ctx context.Context, in *MemoryQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MemoryEntry], error)
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
	// Task Scheduler
	EnqueueTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	GetPendingTasks(ctx context.Context, in *PendingRequest, opts ...grpc.CallOption) (*PendingResponse, error)
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*Empty, error)
}

type hubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHubServiceClient(cc grpc.ClientConnInterface) HubServiceClient {
	return &hubServiceClient{cc}
}

func (c *hubServiceClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, HubService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) WatchHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HealthUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubService_ServiceDesc.Streams[0], HubService_WatchHealth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, HealthUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_WatchHealthClient = grpc.ServerStreamingClient[HealthUpdate]

func (c *hubServiceClient) WatchEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubService_ServiceDesc.Streams[1], HubService_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_WatchEventsClient = grpc.ServerStreamingClient[Event]

func (c *hubServiceClient) ScanProject(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, HubService_ScanProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) AnalyzeFile(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_AnalyzeFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) AnalyzeStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AnalyzeRequest, AnalyzeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubService_ServiceDesc.Streams[2], HubService_AnalyzeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalyzeRequest, AnalyzeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_AnalyzeStreamClient = grpc.BidiStreamingClient[AnalyzeRequest, AnalyzeResponse]

func (c *hubServiceClient) GetDependencies(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_GetDependencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) Deduplicate(ctx context.Context, in *DeduplicateRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_Deduplicate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) Fingerprint(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_Fingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) DiscoverIdentity(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_DiscoverIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) IndexProject(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_IndexProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) ScanTopology(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_ScanTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetContext(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_GetContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetConnectivity(ctx context.Context, in *ConnectivityRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_GetConnectivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) Audit(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_Audit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_Batch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) Reason(ctx context.Context, in *ReasonRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_Reason_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) Patterns(ctx context.Context, in *PatternRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_Patterns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) Penalty(ctx context.Context, in *PenaltyRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_Penalty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) CalculateScore(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_CalculateScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) AuditCoverage(ctx context.Context, in *CoverageRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_AuditCoverage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetKnowledgeGraph(ctx context.Context, in *GraphRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_GetKnowledgeGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) QueryKnowledgeGraph(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_QueryKnowledgeGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) ExecuteHealing(ctx context.Context, in *HealingPlan, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, HubService_ExecuteHealing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) RequestPeerReview(ctx context.Context, in *PeerReviewRequest, opts ...grpc.CallOption) (*PeerReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerReviewResponse)
	err := c.cc.Invoke(ctx, HubService_RequestPeerReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) BroadcastSignal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HubService_BroadcastSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) Remember(ctx context.Context, in *MemoryEntry, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HubService_Remember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) Retrieve(ctx context.Context, in *MemoryQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MemoryEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubService_ServiceDesc.Streams[3], HubService_Retrieve_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MemoryQuery, MemoryEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_RetrieveClient = grpc.ServerStreamingClient[MemoryEntry]

func (c *hubServiceClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, HubService_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) EnqueueTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, HubService_EnqueueTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetPendingTasks(ctx context.Context, in *PendingRequest, opts ...grpc.CallOption) (*PendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PendingResponse)
	err := c.cc.Invoke(ctx, HubService_GetPendingTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, HubService_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HubServiceServer is the server API for HubService service.
// All implementations must embed UnimplementedHubServiceServer
// for forward compatibility.
type HubServiceServer interface {
	// Health & Monitoring
	GetStatus(context.Context, *Empty) (*StatusResponse, error)
	WatchHealth(*Empty, grpc.ServerStreamingServer[HealthUpdate]) error
	WatchEvents(*Empty, grpc.ServerStreamingServer[Event]) error
	// Discovery & Analysis
	ScanProject(context.Context, *ScanRequest) (*ScanResponse, error)
	AnalyzeFile(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	AnalyzeStream(grpc.BidiStreamingServer[AnalyzeRequest, AnalyzeResponse]) error
	GetDependencies(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	Deduplicate(context.Context, *DeduplicateRequest) (*AnalyzeResponse, error)
	Fingerprint(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	DiscoverIdentity(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	IndexProject(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	ScanTopology(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	GetContext(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	GetConnectivity(context.Context, *ConnectivityRequest) (*AnalyzeResponse, error)
	Audit(context.Context, *AuditRequest) (*AnalyzeResponse, error)
	Batch(context.Context, *BatchRequest) (*AnalyzeResponse, error)
	Reason(context.Context, *ReasonRequest) (*AnalyzeResponse, error)
	Patterns(context.Context, *PatternRequest) (*AnalyzeResponse, error)
	Penalty(context.Context, *PenaltyRequest) (*AnalyzeResponse, error)
	CalculateScore(context.Context, *ScoreRequest) (*AnalyzeResponse, error)
	AuditCoverage(context.Context, *CoverageRequest) (*AnalyzeResponse, error)
	GetKnowledgeGraph(context.Context, *GraphRequest) (*AnalyzeResponse, error)
	QueryKnowledgeGraph(context.Context, *QueryRequest) (*AnalyzeResponse, error)
	// Auto-Healing
	ExecuteHealing(context.Context, *HealingPlan) (*AnalyzeResponse, error)
	// Swarm Intelligence (Agent Collaboration)
	RequestPeerReview(context.Context, *PeerReviewRequest) (*PeerReviewResponse, error)
	BroadcastSignal(context.Context, *SignalRequest) (*Empty, error)
	// Semantic Memory
	Remember(context.Context, *MemoryEntry) (*Empty, error)
	Retrieve(*MemoryQuery, grpc.ServerStreamingServer[MemoryEntry]) error
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	// Task Scheduler
	EnqueueTask(context.Context, *TaskRequest) (*TaskResponse, error)
	GetPendingTasks(context.Context, *PendingRequest) (*PendingResponse, error)
	UpdateTask(context.Context, *UpdateTaskRequest) (*Empty, error)
	mustEmbedUnimplementedHubServiceServer()
}

// UnimplementedHubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHubServiceServer struct{}

func (UnimplementedHubServiceServer) GetStatus(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedHubServiceServer) WatchHealth(*Empty, grpc.ServerStreamingServer[HealthUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchHealth not implemented")
}
func (UnimplementedHubServiceServer) WatchEvents(*Empty, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedHubServiceServer) ScanProject(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanProject not implemented")
}
func (UnimplementedHubServiceServer) AnalyzeFile(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeFile not implemented")
}
func (UnimplementedHubServiceServer) AnalyzeStream(grpc.BidiStreamingServer[AnalyzeRequest, AnalyzeResponse]) error {
	return status.Error(codes.Unimplemented, "method AnalyzeStream not implemented")
}
func (UnimplementedHubServiceServer) GetDependencies(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDependencies not implemented")
}
func (UnimplementedHubServiceServer) Deduplicate(context.Context, *DeduplicateRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deduplicate not implemented")
}
func (UnimplementedHubServiceServer) Fingerprint(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fingerprint not implemented")
}
func (UnimplementedHubServiceServer) DiscoverIdentity(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverIdentity not implemented")
}
func (UnimplementedHubServiceServer) IndexProject(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexProject not implemented")
}
func (UnimplementedHubServiceServer) ScanTopology(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanTopology not implemented")
}
func (UnimplementedHubServiceServer) GetContext(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContext not implemented")
}
func (UnimplementedHubServiceServer) GetConnectivity(context.Context, *ConnectivityRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnectivity not implemented")
}
func (UnimplementedHubServiceServer) Audit(context.Context, *AuditRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Audit not implemented")
}
func (UnimplementedHubServiceServer) Batch(context.Context, *BatchRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Batch not implemented")
}
func (UnimplementedHubServiceServer) Reason(context.Context, *ReasonRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reason not implemented")
}
func (UnimplementedHubServiceServer) Patterns(context.Context, *PatternRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Patterns not implemented")
}
func (UnimplementedHubServiceServer) Penalty(context.Context, *PenaltyRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Penalty not implemented")
}
func (UnimplementedHubServiceServer) CalculateScore(context.Context, *ScoreRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateScore not implemented")
}
func (UnimplementedHubServiceServer) AuditCoverage(context.Context, *CoverageRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuditCoverage not implemented")
}
func (UnimplementedHubServiceServer) GetKnowledgeGraph(context.Context, *GraphRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKnowledgeGraph not implemented")
}
func (UnimplementedHubServiceServer) QueryKnowledgeGraph(context.Context, *QueryRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryKnowledgeGraph not implemented")
}
func (UnimplementedHubServiceServer) ExecuteHealing(context.Context, *HealingPlan) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteHealing not implemented")
}
func (UnimplementedHubServiceServer) RequestPeerReview(context.Context, *PeerReviewRequest) (*PeerReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPeerReview not implemented")
}
func (UnimplementedHubServiceServer) BroadcastSignal(context.Context, *SignalRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadcastSignal not implemented")
}
func (UnimplementedHubServiceServer) Remember(context.Context, *MemoryEntry) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Remember not implemented")
}
func (UnimplementedHubServiceServer) Retrieve(*MemoryQuery, grpc.ServerStreamingServer[MemoryEntry]) error {
	return status.Error(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedHubServiceServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedHubServiceServer) EnqueueTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueTask not implemented")
}
func (UnimplementedHubServiceServer) GetPendingTasks(context.Context, *PendingRequest) (*PendingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingTasks not implemented")
}
func (UnimplementedHubServiceServer) UpdateTask(context.Context, *UpdateTaskRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedHubServiceServer) mustEmbedUnimplementedHubServiceServer() {}
func (UnimplementedHubServiceServer) testEmbeddedByValue()                    {}

// UnsafeHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubServiceServer will
// result in compilation errors.
type UnsafeHubServiceServer interface {
	mustEmbedUnimplementedHubServiceServer()
}

func RegisterHubServiceServer(s grpc.ServiceRegistrar, srv HubServiceServer) {
	// If the following call panics, it indicates UnimplementedHubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HubService_ServiceDesc, srv)
}

func _HubService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_WatchHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubServiceServer).WatchHealth(m, &grpc.GenericServerStream[Empty, HealthUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_WatchHealthServer = grpc.ServerStreamingServer[HealthUpdate]

func _HubService_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubServiceServer).WatchEvents(m, &grpc.GenericServerStream[Empty, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_WatchEventsServer = grpc.ServerStreamingServer[Event]

func _HubService_ScanProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).ScanProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_ScanProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).ScanProject(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_AnalyzeFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).AnalyzeFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_AnalyzeFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).AnalyzeFile(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_AnalyzeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HubServiceServer).AnalyzeStream(&grpc.GenericServerStream[AnalyzeRequest, AnalyzeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_AnalyzeStreamServer = grpc.BidiStreamingServer[AnalyzeRequest, AnalyzeResponse]

func _HubService_GetDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetDependencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetDependencies(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_Deduplicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeduplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).Deduplicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_Deduplicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).Deduplicate(ctx, req.(*DeduplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_Fingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).Fingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_Fingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).Fingerprint(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_DiscoverIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).DiscoverIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_DiscoverIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).DiscoverIdentity(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_IndexProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).IndexProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_IndexProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).IndexProject(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_ScanTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).ScanTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_ScanTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).ScanTopology(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetContext(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetConnectivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetConnectivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetConnectivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetConnectivity(ctx, req.(*ConnectivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_Audit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).Audit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_Audit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).Audit(ctx, req.(*AuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_Batch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).Batch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_Batch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).Batch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_Reason_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReasonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).Reason(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_Reason_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).Reason(ctx, req.(*ReasonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_Patterns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatternRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).Patterns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_Patterns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).Patterns(ctx, req.(*PatternRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_Penalty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PenaltyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).Penalty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_Penalty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).Penalty(ctx, req.(*PenaltyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_CalculateScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).CalculateScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_CalculateScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).CalculateScore(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_AuditCoverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).AuditCoverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_AuditCoverage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).AuditCoverage(ctx, req.(*CoverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetKnowledgeGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetKnowledgeGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetKnowledgeGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetKnowledgeGraph(ctx, req.(*GraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_QueryKnowledgeGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).QueryKnowledgeGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_QueryKnowledgeGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).QueryKnowledgeGraph(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_ExecuteHealing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealingPlan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).ExecuteHealing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_ExecuteHealing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).ExecuteHealing(ctx, req.(*HealingPlan))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_RequestPeerReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).RequestPeerReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_RequestPeerReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).RequestPeerReview(ctx, req.(*PeerReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_BroadcastSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).BroadcastSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_BroadcastSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).BroadcastSignal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_Remember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).Remember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_Remember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).Remember(ctx, req.(*MemoryEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_Retrieve_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MemoryQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubServiceServer).Retrieve(m, &grpc.GenericServerStream[MemoryQuery, MemoryEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_RetrieveServer = grpc.ServerStreamingServer[MemoryEntry]

func _HubService_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_EnqueueTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).EnqueueTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_EnqueueTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).EnqueueTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetPendingTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetPendingTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetPendingTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetPendingTasks(ctx, req.(*PendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HubService_ServiceDesc is the grpc.ServiceDesc for HubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hub.HubService",
	HandlerType: (*HubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _HubService_GetStatus_Handler,
		},
		{
			MethodName: "ScanProject",
			Handler:    _HubService_ScanProject_Handler,
		},
		{
			MethodName: "AnalyzeFile",
			Handler:    _HubService_AnalyzeFile_Handler,
		},
		{
			MethodName: "GetDependencies",
			Handler:    _HubService_GetDependencies_Handler,
		},
		{
			MethodName: "Deduplicate",
			Handler:    _HubService_Deduplicate_Handler,
		},
		{
			MethodName: "Fingerprint",
			Handler:    _HubService_Fingerprint_Handler,
		},
		{
			MethodName: "DiscoverIdentity",
			Handler:    _HubService_DiscoverIdentity_Handler,
		},
		{
			MethodName: "IndexProject",
			Handler:    _HubService_IndexProject_Handler,
		},
		{
			MethodName: "ScanTopology",
			Handler:    _HubService_ScanTopology_Handler,
		},
		{
			MethodName: "GetContext",
			Handler:    _HubService_GetContext_Handler,
		},
		{
			MethodName: "GetConnectivity",
			Handler:    _HubService_GetConnectivity_Handler,
		},
		{
			MethodName: "Audit",
			Handler:    _HubService_Audit_Handler,
		},
		{
			MethodName: "Batch",
			Handler:    _HubService_Batch_Handler,
		},
		{
			MethodName: "Reason",
			Handler:    _HubService_Reason_Handler,
		},
		{
			MethodName: "Patterns",
			Handler:    _HubService_Patterns_Handler,
		},
		{
			MethodName: "Penalty",
			Handler:    _HubService_Penalty_Handler,
		},
		{
			MethodName: "CalculateScore",
			Handler:    _HubService_CalculateScore_Handler,
		},
		{
			MethodName: "AuditCoverage",
			Handler:    _HubService_AuditCoverage_Handler,
		},
		{
			MethodName: "GetKnowledgeGraph",
			Handler:    _HubService_GetKnowledgeGraph_Handler,
		},
		{
			MethodName: "QueryKnowledgeGraph",
			Handler:    _HubService_QueryKnowledgeGraph_Handler,
		},
		{
			MethodName: "ExecuteHealing",
			Handler:    _HubService_ExecuteHealing_Handler,
		},
		{
			MethodName: "RequestPeerReview",
			Handler:    _HubService_RequestPeerReview_Handler,
		},
		{
			MethodName: "BroadcastSignal",
			Handler:    _HubService_BroadcastSignal_Handler,
		},
		{
			MethodName: "Remember",
			Handler:    _HubService_Remember_Handler,
		},
		{
			MethodName: "Embed",
			Handler:    _HubService_Embed_Handler,
		},
		{
			MethodName: "EnqueueTask",
			Handler:    _HubService_EnqueueTask_Handler,
		},
		{
			MethodName: "GetPendingTasks",
			Handler:    _HubService_GetPendingTasks_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _HubService_UpdateTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchHealth",
			Handler:       _HubService_WatchHealth_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchEvents",
			Handler:       _HubService_WatchEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AnalyzeStream",
			Handler:       _HubService_AnalyzeStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Retrieve",
			Handler:       _HubService_Retrieve_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hub.proto",
}

const (
	RuleProvider_GetRules_FullMethodName    = "/hub.RuleProvider/GetRules"
	RuleProvider_AnalyzeCode_FullMethodName = "/hub.RuleProvider/AnalyzeCode"
)

// RuleProviderClient is the client API for RuleProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuleProviderClient interface {
	GetRules(ctx context.Context, in *RuleRequest, opts ...grpc.CallOption) (*RuleResponse, error)
	AnalyzeCode(ctx context.Context, in *AnalyzeCodeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
}

type ruleProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleProviderClient(cc grpc.ClientConnInterface) RuleProviderClient {
	return &ruleProviderClient{cc}
}

func (c *ruleProviderClient) GetRules(ctx context.Context, in *RuleRequest, opts ...grpc.CallOption) (*RuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuleResponse)
	err := c.cc.Invoke(ctx, RuleProvider_GetRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleProviderClient) AnalyzeCode(ctx context.Context, in *AnalyzeCodeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, RuleProvider_AnalyzeCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleProviderServer is the server API for RuleProvider service.
// All implementations must embed UnimplementedRuleProviderServer
// for forward compatibility.
type RuleProviderServer interface {
	GetRules(context.Context, *RuleRequest) (*RuleResponse, error)
	AnalyzeCode(context.Context, *AnalyzeCodeRequest) (*AnalyzeResponse, error)
	mustEmbedUnimplementedRuleProviderServer()
}

// UnimplementedRuleProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuleProviderServer struct{}

func (UnimplementedRuleProviderServer) GetRules(context.Context, *RuleRequest) (*RuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRules not implemented")
}
func (UnimplementedRuleProviderServer) AnalyzeCode(context.Context, *AnalyzeCodeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeCode not implemented")
}
func (UnimplementedRuleProviderServer) mustEmbedUnimplementedRuleProviderServer() {}
func (UnimplementedRuleProviderServer) testEmbeddedByValue()                      {}

// UnsafeRuleProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuleProviderServer will
// result in compilation errors.
type UnsafeRuleProviderServer interface {
	mustEmbedUnimplementedRuleProviderServer()
}

func RegisterRuleProviderServer(s grpc.ServiceRegistrar, srv RuleProviderServer) {
	// If the following call panics, it indicates UnimplementedRuleProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuleProvider_ServiceDesc, srv)
}

func _RuleProvider_GetRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleProviderServer).GetRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleProvider_GetRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleProviderServer).GetRules(ctx, req.(*RuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleProvider_AnalyzeCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleProviderServer).AnalyzeCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleProvider_AnalyzeCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleProviderServer).AnalyzeCode(ctx, req.(*AnalyzeCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuleProvider_ServiceDesc is the grpc.ServiceDesc for RuleProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuleProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hub.RuleProvider",
	HandlerType: (*RuleProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRules",
			Handler:    _RuleProvider_GetRules_Handler,
		},
		{
			MethodName: "AnalyzeCode",
			Handler:    _RuleProvider_AnalyzeCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub.proto",
}
