from ..base import BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext
import re

class MetricPersona(BaseActivePersona):
    """
    📊 Dr. Metric — PhD in TypeScript Data Telemetry & Logging
    Generated by Sovereign Forge.
    """
    def __init__(self, project_root: str = None):
        super().__init__(project_root)
        self.id = "metric"
        self.name = "Metric"
        self.emoji = "📊"
        self.role = "PhD Observability Engineer"
        self.phd_identity = "TypeScript Data Telemetry & Logging"
        self.stack = "Python"
        self.healing_prompt = "Fix the following metrics or KPI engineering issue. Correct metric calculations and ensure dimensional accuracy. Return ONLY the corrected code or a specific diff."

    async def execute(self, context: ProjectContext) -> list:
        self.set_context(context)
        return await self.perform_audit()

    def get_audit_rules(self) -> dict:
        return {
            "extensions": [".py"],
            "rules": [
                # [
          {
                    "regex": "console\\.log\\(",
                    "issue": "Cegueira: console.log em produção — use logger estruturado.",
                    "severity": "high"
          },
          {
                    "regex": "console\\.error\\(",
                    "issue": "Telemetria Fraca: console.error sem contexto estruturado.",
                    "severity": "medium"
          },
          {
                    "regex": "catch\\s*\\([^)]*\\)\\s*\\{\\s*\\}",
                    "issue": "Cegueira Total: catch vazio engole erros silenciosamente.",
                    "severity": "critical"
          },
          {
                    "regex": "catch\\s*\\([^)]*\\)\\s*\\{[^}]*console\\.log",
                    "issue": "Telemetria Informal: Erro logado via console em vez de logger.",
                    "severity": "medium"
          }
]
            ]
        }

    async def reason_about_objective(self, objective: str, file: str, context: str) -> dict:
        return {
            "file": file,
            "severity": "INFO",
            "issue": f"PhD Metric (Python): Analyzing {objective} in {file}.",
            "context": "analyzing objective"
        }

    async def delegate_healing_to_hub(self, file: str, issue: str) -> str:
        # Delegation logic here via gRPC back to Hub
        return None
