from ..base import BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext
import re

class WebPersona(BaseActivePersona):
    """
    🌐 Dr. Web — PhD in Web Performance & DOM Integrity (TS/Bun)
    Generated by Sovereign Forge.
    """
    def __init__(self, project_root: str = None):
        super().__init__(project_root)
        self.id = "web"
        self.name = "Web"
        self.emoji = "🌐"
        self.role = "PhD Frontend Architect"
        self.phd_identity = "Web Performance & DOM Integrity (TS/Bun)"
        self.stack = "Python"
        self.healing_prompt = ""

    async def execute(self, context: ProjectContext) -> list:
        self.set_context(context)
        return await self.perform_audit()

    def get_audit_rules(self) -> dict:
        return {
            "extensions": [".py"],
            "rules": [
                # [
          {
                    "regex": "useEffect\\(\\(\\) => \\{[^\\]]*\\}, \\[\\]\\)",
                    "issue": "Hydration: Efeitos colaterais no mount sem verificação de window. Verifique se isso queima a hidratação no SSR.",
                    "severity": "medium"
          },
          {
                    "regex": "dangerouslySetInnerHTML",
                    "issue": "Security: Uso de dangerouslySetInnerHTML detectado. Risco de XSS se o conteúdo não for higienizado.",
                    "severity": "high"
          },
          {
                    "regex": "document\\.getElementById",
                    "issue": "DOM: Manipulação direta do DOM via 'document'. Prefira refs ou estados reativos para manter a integridade do VDOM.",
                    "severity": "low"
          }
]
            ]
        }

    async def reason_about_objective(self, objective: str, file: str, context: str) -> dict:
        return {
            "file": file,
            "severity": "INFO",
            "issue": f"PhD Web (Python): Analyzing {objective} in {file}.",
            "context": "analyzing objective"
        }

    async def delegate_healing_to_hub(self, file: str, issue: str) -> str:
        # Delegation logic here via gRPC back to Hub
        return None
