use crate::core::base::{BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext};
use crate::core::types::MetricData;

/**
 * ⚡ Dr. Bolt — PhD in Low-Latency & Concurrency Optimization
 * Generated by Sovereign Forge.
 */
pub struct BoltPersona {
    base: BaseActivePersona,
}

impl BoltPersona {
    pub fn new(project_root: Option<String>) -> Self {
        Self {
            base: BaseActivePersona::new(
                "Bolt".to_string(),
                "⚡".to_string(),
                "PhD Performance Engineer".to_string(),
                "Low-Latency & Concurrency Optimization".to_string(),
                "Rust".to_string(),
                "Refactor the following code to improve performance and concurrency as per PhD standards. Use high-efficiency patterns (e.g., replace forEach with for-of, minimize lock contention). Return ONLY the corrected code or a specific diff.".to_string(),
                project_root,
            ),
        }
    }

    pub fn get_audit_rules(&self) -> (Vec<String>, Vec<AuditRule>) {
        (
            [".rs"].iter().map(|s| s.to_string()).collect(),
            vec![
                /* [
          {
                    "regex": "\\.forEach\\(",
                    "issue": "Performance: forEach detectado. Use for-of ou for loops em caminhos críticos para otimização JIT PhD.",
                    "severity": "medium"
          },
          {
                    "regex": "new Array\\(\\)",
                    "issue": "Performance: Alocação de array vazia. Use literais ou pré-alocação se o tamanho for conhecido PhD.",
                    "severity": "low"
          }
] */
            ]
        )
    }

    pub fn perform_audit(&self) {
        println!("🦀 [{}] Starting fleet-wide audit via Hub PhD...", self.base.name);
        // delegation logic using tonic gRPC client
        // The original comment "Logic will be delegated via gRPC HubClient."
        // and "Vec::new()" were likely placeholders for this delegation.
    }

    pub fn reason_about_objective(&self, objective: &str, file: &str, context: &str) {
        println!("🦀 [{}] Delegating reasoning for '{}' to Hub...", self.base.name, objective);
    }

    pub fn delegate_healing_to_hub(&self, file: &str, issue: &str) {
        println!("🦀 [{}] Delegating healing for '{}' to Hub...", self.base.name, issue);
    }
}
