use crate::core::base::{BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext};
use crate::core::types::MetricData;

/**
 * 🛡️ Dr. Strict — PhD in Type Safety & Memory Purity
 * Generated by Sovereign Forge.
 */
pub struct StrictPersona {
    base: BaseActivePersona,
}

impl StrictPersona {
    pub fn new(project_root: Option<String>) -> Self {
        Self {
            base: BaseActivePersona::new(
                "Strict".to_string(),
                "🛡️".to_string(),
                "PhD Security & Type Integrity".to_string(),
                "Type Safety & Memory Purity".to_string(),
                "Rust".to_string(),
                "Fix the following architectural or security violation. Ensure compliance with strict PhD guidelines (e.g., remove eval, enforce type safety, sanitize inputs). Return ONLY the corrected code or a specific diff.".to_string(),
                project_root,
            ),
        }
    }

    pub fn get_audit_rules(&self) -> (Vec<String>, Vec<AuditRule>) {
        (
            [".rs"].iter().map(|s| s.to_string()).collect(),
            vec![
                /* [
          {
                    "regex": "as any",
                    "issue": "Integridade: Cast 'as any' detectado. Viola a segurança de tipos PhD.",
                    "severity": "critical"
          },
          {
                    "regex": "!",
                    "issue": "Integridade: Operador de asserção não-nula (!) detectado. Risco de runtime panic PhD.",
                    "severity": "high"
          }
] */
            ]
        )
    }

    pub fn perform_audit(&self) {
        println!("🦀 [{}] Starting fleet-wide audit via Hub PhD...", self.base.name);
        // delegation logic using tonic gRPC client
        // The original comment "Logic will be delegated via gRPC HubClient."
        // and "Vec::new()" were likely placeholders for this delegation.
    }

    pub fn reason_about_objective(&self, objective: &str, file: &str, context: &str) {
        println!("🦀 [{}] Delegating reasoning for '{}' to Hub...", self.base.name, objective);
    }

    pub fn delegate_healing_to_hub(&self, file: &str, issue: &str) {
        println!("🦀 [{}] Delegating healing for '{}' to Hub...", self.base.name, issue);
    }
}
