import { BaseActivePersona } from "../../base.ts";
import type { AuditRule, StrategicFinding, AuditFinding, HealingResult, ProjectContext } from "../../base.ts";

/**
 * 📝 Dr. Scribe — PhD in Documentation & Knowledge Transfer (TypeScript)
 * Generated by Sovereign Forge.
 */
export class ScribePersona extends BaseActivePersona {
    constructor(projectRoot: string | undefined = undefined) {
        super(projectRoot);
        this.id = "scribe";
        this.name = "Scribe";
        this.emoji = "📝";
        this.role = "PhD Documentation Engineer";
        this.phd_identity = "Documentation & Knowledge Transfer (TypeScript)";
        this.stack = "TypeScript";
        this.healingPrompt = "Fix the following documentation or API specification issue. Complete JSDoc annotations and ensure OpenAPI spec accuracy. Return ONLY the corrected code or a specific diff.";
    }

    override async execute(context: ProjectContext): Promise<(AuditFinding | StrategicFinding)[]> {
        this.setContext(context);
        if (this.healingPrompt) {
            const { findings } = await this.auditAndHeal();
            return findings;
        }
        const findings = await this.performAudit();
        return findings;
    }

    override getAuditRules(): { extensions: string[]; rules: AuditRule[] } {
        return {
            extensions: [".ts",".tsx"],
            rules: [
          {
                    "regex": "^export\\s+(?:async\\s+)?(? :function|class|const|interface|type|enum)\\s+\\w+",
                    "issue": "Amnésia Técnica: Exportação sem JSDoc detectada.",
                    "severity": "high"
          }
]
        };
    }

    public override async performAudit(): Promise<AuditFinding[]> {
        this.startMetrics();
        
        const allFindings: AuditFinding[] = [];
        const files = Object.keys(this.contextData);
        
        for (const file of files) {
            const results = await this.delegateAuditToHub(file);
            // Inject file path if hub didn't (hub uses 'embedded_content' for raw content)
            results.forEach(f => {
                if (f.file === "embedded_content") f.file = file;
                allFindings.push(f);
            });
        }
        
        this.endMetrics(allFindings.length);
        return allFindings;
    }

    public override async reasonAboutObjective(objective: string, file: string, context: string): Promise<StrategicFinding | null> {
        return await super.reasonAboutObjective(objective, file, context);
    }

    override selfDiagnostic(): any {
        return { status: "Soberano", score: 100, details: "Módulo Scribe operando com paridade total via Forge." };
    }

    override getSystemPrompt(): string {
        return `Você é o Dr. Scribe, PhD em Documentation & Knowledge Transfer (TypeScript). Sua missão é garantir a excelência via governança PhD.`;
    }
}
