use crate::core::base::{BaseActivePersona, AuditRule, AuditFinding, StrategicFinding, ProjectContext};
use crate::core::types::MetricData;

/**
 * 🏛️ Dr. Director — PhD in Systemic Orchestration & AI Governance
 * Generated by Sovereign Forge.
 */
pub struct DirectorPersona {
    base: BaseActivePersona,
}

impl DirectorPersona {
    pub fn new(project_root: Option<String>) -> Self {
        Self {
            base: BaseActivePersona::new(
                "Director".to_string(),
                "🏛️".to_string(),
                "Master Orchestrator".to_string(),
                "Systemic Orchestration & AI Governance".to_string(),
                "Rust".to_string(),
                "Fix the following architectural drift or governance violation. Enforce layered boundaries and ensure proper separation of concerns. Return ONLY the corrected code or a specific diff.".to_string(),
                project_root,
            ),
        }
    }

    pub fn get_audit_rules(&self) -> (Vec<String>, Vec<AuditRule>) {
        (
            [".rs"].iter().map(|s| s.to_string()).collect(),
            vec![
                /* [
          {
                    "regex": "security(?!.*crypto)",
                    "issue": "Alerta Estratégico: Arquivo de segurança sem referências criptográficas óbvias PhD.",
                    "severity": "low"
          }
] */
            ]
        )
    }

    pub fn perform_audit(&self) {
        println!("🦀 [{}] Starting fleet-wide audit via Hub PhD...", self.base.name);
        // delegation logic using tonic gRPC client
        // The original comment "Logic will be delegated via gRPC HubClient."
        // and "Vec::new()" were likely placeholders for this delegation.
    }

    pub fn reason_about_objective(&self, objective: &str, file: &str, context: &str) {
        println!("🦀 [{}] Delegating reasoning for '{}' to Hub...", self.base.name, objective);
    }

    pub fn delegate_healing_to_hub(&self, file: &str, issue: &str) {
        println!("🦀 [{}] Delegating healing for '{}' to Hub...", self.base.name, issue);
    }
}
