import 'package:personas_agentes/core/base.dart';

/**
 * 🧪 Dr. Testify — PhD in TypeScript Test Integrity & Coverage
 * Generated by Sovereign Forge.
 */
class TestifyPersona extends BaseActivePersona {
  TestifyPersona({String? projectRoot}) : super(projectRoot) {
    this.name = "Testify";
    this.emoji = "🧪";
    this.role = "PhD Quality & Testing Engineer";
    this.    phdIdentity = "TypeScript Test Integrity & Coverage",
    stack = "Flutter",
    healingPrompt = "Fix the following testing or quality assurance issue. Eliminate flaky tests, improve assertion specificity, and increase coverage. Return ONLY the corrected code or a specific diff.";
  }

  @override
  Future<List<dynamic>> execute(ProjectContext context) async {
    this.setContext(context);
    return await this.performAudit();
  }

  @override
  Map<String, dynamic> getAuditRules() {
    return {
      'extensions': [".dart"],
      'rules': [
        // [
          {
                    "regex": "describe\\s*\\([^)]*\\)\\s*\\{[^}]*describe",
                    "issue": "Complexidade: Testes muito aninhados — divida em arquivos menores PhD.",
                    "severity": "low"
          },
          {
                    "regex": "it\\s*\\([^)]*\\)\\s*\\{\\s*\\}",
                    "issue": "Vazio: Teste sem implementação (placeholder) PhD.",
                    "severity": "high"
          },
          {
                    "regex": "expect\\([^)]*\\)\\.toBeDefined\\(\\)",
                    "issue": "Fraco: toBeDefined() é uma asserção fraca — use valores específicos PhD.",
                    "severity": "medium"
          }
]
      ],
    };
  }

  Future<void> performAudit() async {
    print("💙 [${name}] Starting fleet-wide audit via Hub PhD...");
    // delegation logic here using a gRPC client stub
  }

  void reasonAboutObjective(String objective, String file, String context) {
    print("💙 [${name}] Delegating reasoning for '${objective}' to Hub...");
  }

  void delegateHealingToHub(String file, String issue) {
    print("💙 [${name}] Delegating healing for '$issue' to Hub...");
  }
}
