import { BaseActivePersona } from "../../base.ts";
import type { AuditRule, StrategicFinding, AuditFinding, HealingResult, ProjectContext } from "../../base.ts";

/**
 * 🛸 Dr. Voyager — PhD in Legacy Modernization & Future-Proofing (TypeScript)
 * Generated by Sovereign Forge.
 */
export class VoyagerPersona extends BaseActivePersona {
    constructor(projectRoot: string | undefined = undefined) {
        super(projectRoot);
        this.id = "voyager";
        this.name = "Voyager";
        this.emoji = "🛸";
        this.role = "PhD Modernization Architect";
        this.phd_identity = "Legacy Modernization & Future-Proofing (TypeScript)";
        this.stack = "Bun";
        this.healingPrompt = "Fix the following migration or version upgrade issue. Replace deprecated API usage and ensure backward compatibility. Return ONLY the corrected code or a specific diff.";
    }

    override async execute(context: ProjectContext): Promise<(AuditFinding | StrategicFinding)[]> {
        this.setContext(context);
        if (this.healingPrompt) {
            const { findings } = await this.auditAndHeal();
            return findings;
        }
        const findings = await this.performAudit();
        return findings;
    }

    override getAuditRules(): { extensions: string[]; rules: AuditRule[] } {
        return {
            extensions: [".ts",".js"],
            rules: [
          {
                    "regex": "var\\s+",
                    "issue": "Legado: Uso de 'var' detectado. Use 'const' ou 'let' PhD.",
                    "severity": "high"
          },
          {
                    "regex": "module\\.exports",
                    "issue": "Legado: CommonJS detectado. Use ESM (export/import) PhD.",
                    "severity": "medium"
          }
]
        };
    }

    public override async performAudit(): Promise<AuditFinding[]> {
        this.startMetrics();
        
        const allFindings: AuditFinding[] = [];
        const files = Object.keys(this.contextData);
        
        for (const file of files) {
            const results = await this.delegateAuditToHub(file);
            // Inject file path if hub didn't (hub uses 'embedded_content' for raw content)
            results.forEach(f => {
                if (f.file === "embedded_content") f.file = file;
                allFindings.push(f);
            });
        }
        
        this.endMetrics(allFindings.length);
        return allFindings;
    }

    public override async reasonAboutObjective(objective: string, file: string, context: string): Promise<StrategicFinding | null> {
        return await super.reasonAboutObjective(objective, file, context);
    }

    override selfDiagnostic(): any {
        return { status: "Soberano", score: 100, details: "Módulo Voyager operando com paridade total via Forge." };
    }

    override getSystemPrompt(): string {
        return `Você é o Dr. Voyager, PhD em Legacy Modernization & Future-Proofing (TypeScript). Sua missão é garantir a excelência via governança PhD.`;
    }
}
